// test_pipeline_direct_if_albq.c — gr-iridium "path C" host A/B
//
// Bypass the polyphase channelizer AND the 40->250 kHz resampler.
// Read per-burst cf32 baseband dumps produced by
// tests/scripts/direct_if_dump.py (which mirrors gr-iridium's
// burst_downmix: rotate raw 2.5 MSPS to DC at the tagged offset,
// LPF + decimate 10x to 250 ksps). Feed each dump to the SAME
// burst_pipeline_process_250khz() that runs on P4, and count
// decodes against gr-iridium's ground truth.
//
// The point of this test:
//   - 50+/65 -> our downstream pipeline is fine; the channelizer
//               + resampler are the entire gap.
//   - low N  -> downstream has bugs that no front-end fix will fix.
//
// Inputs (generated by direct_if_dump.py):
//   /tmp/host_direct_if/manifest.csv
//   /tmp/host_direct_if/burst_<NNN>.cf32

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>

#include "burst_pipeline.h"
#include "qpsk_demod.h"
#include "uw_correlator.h"

#define MANIFEST_PATH "/tmp/host_direct_if/manifest.csv"
#define BURST_DIR     "/tmp/host_direct_if"
#define MAX_BURSTS    1024
#define MAX_SAMPLES   65536          // 250 ksps * (1.6+16+...) ms headroom

typedef struct {
    int   idx;             // path-C enumeration order
    int   gri_burst_id;    // gri's internal burst ID (from RAW "I:" field)
    double timestamp_ms;
    long  abs_freq_hz;
    long  freq_offset_hz;
    int   n_samples_250k;
    int   confidence_pct;
    char  filename[64];
} manifest_entry_t;

static int load_manifest(manifest_entry_t *entries, int max_n) {
    FILE *fh = fopen(MANIFEST_PATH, "r");
    if (!fh) {
        fprintf(stderr, "manifest missing: %s\n"
                        "  run: python3 tests/scripts/direct_if_dump.py\n",
                        MANIFEST_PATH);
        return -1;
    }
    char line[512];
    if (!fgets(line, sizeof(line), fh)) {       // header
        fclose(fh);
        return 0;
    }
    int n = 0;
    while (n < max_n && fgets(line, sizeof(line), fh)) {
        manifest_entry_t *e = &entries[n];
        if (sscanf(line, "%d,%d,%lf,%ld,%ld,%d,%d,%63s",
                   &e->idx, &e->gri_burst_id, &e->timestamp_ms,
                   &e->abs_freq_hz, &e->freq_offset_hz, &e->n_samples_250k,
                   &e->confidence_pct, e->filename) == 8) {
            n++;
        }
    }
    fclose(fh);
    return n;
}

// Load a cf32 (interleaved float32 IQ) and convert to int16 Q15.
// Returns number of complex samples loaded; writes 2*n int16s.
static int load_cf32_as_sc16(const char *path, int16_t *out, int max_complex) {
    FILE *fh = fopen(path, "rb");
    if (!fh) return -1;
    fseek(fh, 0, SEEK_END);
    long bytes = ftell(fh);
    fseek(fh, 0, SEEK_SET);
    int n_complex = (int)(bytes / 8);   // 2 * float32 = 8 bytes
    if (n_complex > max_complex) n_complex = max_complex;

    static float buf[2 * MAX_SAMPLES];
    size_t got = fread(buf, sizeof(float), 2 * n_complex, fh);
    fclose(fh);
    if ((int)got != 2 * n_complex) return -1;

    // Convert cf32 [-1, +1] to Q15 with the natural scale × 32768.
    // gr-iridium operates on float at the IF baseband's natural
    // amplitude (~0.05-0.15 peak on this fixture); we mirror that
    // by NOT auto-rescaling per burst. Auto-rescaling would force
    // every burst to the same peak amplitude and erase the SNR
    // differences between bursts the downstream chain depends on.
    for (int i = 0; i < 2 * n_complex; i++) {
        float v = buf[i] * 32768.0f;
        if (v >  32767.0f) v =  32767.0f;
        if (v < -32768.0f) v = -32768.0f;
        out[i] = (int16_t)lrintf(v);
    }
    return n_complex;
}

int main(int argc, char **argv) {
    (void)argc; (void)argv;

    static manifest_entry_t entries[MAX_BURSTS];
    int n_entries = load_manifest(entries, MAX_BURSTS);
    if (n_entries < 0) return 2;
    if (n_entries == 0) {
        fprintf(stderr, "manifest empty\n");
        return 2;
    }

    // The Python dumper pre-pads each burst by 1.6 ms (PRE_SAMPLES_RAW=4000
    // at 2.5 MSPS), so at 250 ksps the burst preamble starts at sample
    // PRE_SAMPLES_BB = 400. With CFO_BYPASS_D13=1 the path-C harness
    // skips D13's envelope search and points burst_pipeline directly at
    // that known-good position — isolates downstream defects (CFO,
    // matched filter, PLL) from D13 mispositioning.
    // direct_if_dump.py adds 3.2 ms (8000 raw / 800 @ 250k samples)
    // of pre-pad so the window always starts at-or-before gri's
    // b.start. Used only when CFO_BYPASS_D13 forces a known start.
    const int PRE_SAMPLES_BB = 0;
    const char *bypass_env = getenv("CFO_BYPASS_D13");
    int bypass_d13 = (bypass_env && bypass_env[0] == '1');

    // For stagewise gr-iridium comparison: when set, dump per-stage
    // cf32 signals to /tmp/host_signals/ for this one path-C burst.
    // Example: DUMP_BURST_IDX=0 reproduces gr-iridium's --debug-id 30
    // (the first decoded burst at timestamp 418 ms).
    const char *dump_env = getenv("DUMP_BURST_IDX");
    int dump_burst_idx = dump_env ? atoi(dump_env) : -1;

    printf("path-C direct-IF host test: %d gr-iridium-tagged bursts\n",
           n_entries);
    printf("  source: %s\n", MANIFEST_PATH);
    printf("  D13:    %s\n",
           bypass_d13 ? "BYPASSED (force_start=400)" : "running normally");
    printf("\n");
    printf("%4s %5s %10s %12s %8s %7s %5s %4s %5s %6s %s\n",
           "idx", "gri", "ts_ms", "abs_hz", "off_hz", "nsamp", "bstart",
           "uw", "snr", "omega", "result");
    printf("--------------------------------------------------------------------------------------\n");

    int decoded = 0, pipeline_ok = 0, uw_found = 0;
    static int16_t iq250[2 * MAX_SAMPLES];

    for (int i = 0; i < n_entries; i++) {
        manifest_entry_t *e = &entries[i];
        char path[256];
        snprintf(path, sizeof(path), "%s/%s", BURST_DIR, e->filename);
        int n_complex = load_cf32_as_sc16(path, iq250, MAX_SAMPLES);
        if (n_complex < 0) {
            printf("%4d %10.4f %12ld %8ld %7s %4s %5s %6s %s\n",
                   e->idx, e->timestamp_ms, e->abs_freq_hz, e->freq_offset_hz,
                   "--", "--", "--", "--", "LOAD-FAIL");
            continue;
        }

        burst_pipeline_result_t res;
        memset(&res, 0, sizeof(res));
        if (bypass_d13) burst_pipeline_force_start_once(PRE_SAMPLES_BB);
        if (i == dump_burst_idx) {
            system("mkdir -p /tmp/host_signals");
            burst_pipeline_set_dump_once("/tmp/host_signals");
        }
        bool ok = burst_pipeline_process_250khz(iq250, n_complex, &res);
        if (ok) pipeline_ok++;
        bool have_uw = (res.uw_res.direction != UW_DIR_UNKNOWN);
        if (have_uw) uw_found++;
        if (res.demod_ok) {
            decoded++;
            const char *dir = (res.frame.direction == DIR_DOWNLINK) ? "DL" :
                              (res.frame.direction == DIR_UPLINK)   ? "UL" : "??";
            printf("%4d %5d %10.4f %12ld %8ld %7d %5d %4d %5.1f %+6.3f DECODED-%s (%d bits)\n",
                   e->idx, e->gri_burst_id, e->timestamp_ms,
                   e->abs_freq_hz, e->freq_offset_hz,
                   n_complex, res.burst_start, res.uw_res.uw_offset,
                   res.uw_res.snr_estimate_db, res.omega_coarse,
                   dir, res.frame.n_bits);
            free(res.frame.bits);
        } else {
            const char *why = !ok ? "TOO-SHORT"
                              : (!have_uw ? "no-UW" : "no-demod");
            printf("%4d %5d %10.4f %12ld %8ld %7d %5d %4d %5.1f %+6.3f %s\n",
                   e->idx, e->gri_burst_id, e->timestamp_ms,
                   e->abs_freq_hz, e->freq_offset_hz,
                   n_complex, res.burst_start, res.uw_res.uw_offset,
                   res.uw_res.snr_estimate_db, res.omega_coarse, why);
        }
    }

    printf("\n");
    printf("Summary: %d/%d gr-iridium-decoded bursts ALSO decoded by host pipeline\n",
           decoded, n_entries);
    printf("         (pipeline-ran=%d, UW-found=%d)\n", pipeline_ok, uw_found);

    // Return code: 0 always (this is a measurement, not a regression gate).
    // CI runs it; humans read the numbers.
    return 0;
}
