// Auto-generated by tests/scripts/build_acars_fixture.py — do not edit by hand.
//
// Ground truth: /home/bruce/iridium_bits/acars-milestone-20260706.{parsed,txt}
// (2026-07-06 HydraSDR capture, REG A62001). The expected_* fields below
// come from acars-milestone-20260706.txt, iridium-toolkit's
// `reassembler.py -m acars` output over that capture — an independent
// reference, not derived from this repo's own decode code.
//
// Each message's fragments[] are the REAL, verified-CRC-OK LW.DA burst
// payloads (post-BCH bytes, exactly as iridium-toolkit's ida.py parsed
// them from the capture) in over-the-air order. Every message in this
// capture needs >1 fragment: a single LW.DA burst caps at 24 payload
// bytes (da_len is a 5-bit field) but these ACARS/SBD envelopes run
// 25-37 bytes, so the transmitter split them across consecutive LW.DA
// time slots chained via da_cont/da_ctr — see
// common/iridium_decoder/ida_reassembler.h.
//
// NOTE: this fixture is built at the post-ida_decode() level (raw
// pre-BCH symbol bits for these specific over-the-air bursts are not
// available -- the live capture that produced them has since rotated
// past this time window; only the milestone's derived frame-level
// trace survives). test_acars_tail_real.c therefore exercises
// ida_reassembler_feed() -> sbd_reassembler_feed() -> libacars against
// real captured content, while iridium_frame_classify()/ida_decode()'s
// own BCH path is covered separately by the Albuquerque corpus tests
// (test_iridium_frame_corpus, test_ida_decode_corpus).
#pragma once
#include <stdint.h>
#include <stdbool.h>

typedef struct {
    uint8_t        da_cont;
    uint8_t        da_ctr;
    const uint8_t *payload;
    uint8_t        payload_len;
    uint32_t       freq_hz;
    uint64_t       timestamp_us;
} acars_fixture_fragment_t;

typedef struct {
    const char                     *description;
    const acars_fixture_fragment_t *fragments;
    int                             n_fragments;
    bool                            uplink;
    const char                     *expected_reg;
    char                            expected_mode;
    uint8_t                         expected_label[2];
    char                            expected_block_id;
    char                            expected_ack;
    const char                     *expected_txt;
    const char                     *expected_timestamp_iso;
} acars_fixture_message_t;

static const uint8_t                  ACARS_FIX_0_F0_PAYLOAD[] = {0x76, 0x08, 0x26, 0xe1, 0x03, 0x01, 0x00, 0x63, 0xe2, 0x10, 0x19, 0x01, 0x01, 0x03, 0xab, 0x01, 0x01, 0x00, 0x00, 0x00};
static const uint8_t                  ACARS_FIX_0_F1_PAYLOAD[] = {0x01, 0x32, 0xae, 0xc1, 0xb6, 0x32, 0xb0, 0xb0, 0x31, 0xb3, 0xdf, 0x7f, 0x4f, 0x83, 0x4d, 0xc4, 0x7f};
static const acars_fixture_fragment_t ACARS_FIX_0_FRAGMENTS[]  = {
    {1, 0u, ACARS_FIX_0_F0_PAYLOAD, 20u, 1622750211u, 1783308379527252ULL},
    {0, 1u, ACARS_FIX_0_F1_PAYLOAD, 17u, 1622750201u, 1783308379617254ULL},
};

static const uint8_t                  ACARS_FIX_1_F0_PAYLOAD[] = {0x76, 0x08, 0x26, 0xe1, 0x1a, 0x01, 0x00, 0xf8, 0x94, 0x10, 0x19, 0x01, 0x01, 0x03, 0xc2, 0x01, 0x01, 0x00, 0x00, 0x00};
static const uint8_t                  ACARS_FIX_1_F1_PAYLOAD[] = {0x01, 0x32, 0xae, 0xc1, 0xb6, 0x32, 0xb0, 0xb0, 0x31, 0xb6, 0xdf, 0x7f, 0x4c, 0x83, 0x71, 0xc8, 0x7f};
static const acars_fixture_fragment_t ACARS_FIX_1_FRAGMENTS[]  = {
    {1, 0u, ACARS_FIX_1_F0_PAYLOAD, 20u, 1622052850u, 1783309370788778ULL},
    {0, 1u, ACARS_FIX_1_F1_PAYLOAD, 17u, 1622052845u, 1783309370878777ULL},
};

#define ACARS_FIXTURE_NUM_MESSAGES 2
static const acars_fixture_message_t ACARS_FIXTURE_MESSAGES[ACARS_FIXTURE_NUM_MESSAGES] = {
    {"2026-07-06T03:26:19Z REG:A62001 ACK:3 bID:O", ACARS_FIX_0_FRAGMENTS, 2, false, "A62001", '2', {0x5fu, 0x7fu}, 'O', '3', "", "2026-07-06T03:26:19Z"},
    {"2026-07-06T03:42:50Z REG:A62001 ACK:6 bID:L", ACARS_FIX_1_FRAGMENTS, 2, false, "A62001", '2', {0x5fu, 0x7fu}, 'L', '6', "", "2026-07-06T03:42:50Z"},
};
