// See uw_correlator.h.
//
// Algorithm:
//   For each candidate UW start position k:
//     corr_dl[k] = | sum_{i=0..11}  uw_dl_cplx[i] * conj(burst[k + 2i]) |²
//     corr_ul[k] = | sum_{i=0..11}  uw_ul_cplx[i] * conj(burst[k + 2i]) |²
//   Find peak across all k for both DL and UL. Pick the larger.
//   Parabolic interpolation of the 3 bins around the peak gives sub-
//   sample timing precision.
//
// uw_dl_cplx[i] is the DL UW pattern mapped to BPSK constellation:
//   IR_UW_DL[i] = 0  → +1 + j      (quadrant 0)
//   IR_UW_DL[i] = 2  → -1 - j      (quadrant 2)
//   (UW values are always {0, 2} — see iridium.h)
// Similarly for UL.
//
// Symbol stride: at 2 sps, consecutive UW symbols are 2 burst samples
// apart. So we step burst by 2 between each UW symbol comparison.

#include "uw_correlator.h"
#if __has_include("esp_attr.h")
#include "esp_attr.h"
#else
// Host build: EXT_RAM_BSS_ATTR is a no-op (only one address space).
#define EXT_RAM_BSS_ATTR
#endif

#include <math.h>
#include <stdbool.h>
#include <string.h>

#define UW_LENGTH        12
#define PREAMBLE_LENGTH  16
#define SYNC_LENGTH      (PREAMBLE_LENGTH + UW_LENGTH)   // 28
// SYM_STRIDE = UW_SPS (10) to match gr-iridium's burst_downmix
// internal rate. Worker now produces a 250 kHz / 10 sps stream into
// these functions (was 50 kHz / 2 sps). Host tests must synthesize
// at 10 sps too.
#define SYM_STRIDE       UW_SPS  // = 10 samples per symbol

// Modified Bessel function I0(x), polynomial approximation
// (Abramowitz & Stegun 9.8). Used by the Kaiser-windowed start-finder LP.
static float bessel_i0(float x)
{
    float ax = (x < 0.0f) ? -x : x;
    if (ax < 3.75f) {
        float y = x / 3.75f;
        y = y * y;
        return 1.0f + y * (3.5156229f + y * (3.0899424f + y * (1.2067492f
              + y * (0.2659732f + y * (0.0360768f + y * 0.0045813f)))));
    }
    float y = 3.75f / ax;
    return (expf(ax) / sqrtf(ax)) * (0.39894228f + y * (0.01328592f
           + y * (0.00225319f + y * (-0.00157565f + y * (0.00916281f
           + y * (-0.02057706f + y * (0.02635537f + y * (-0.01647633f
           + y * 0.00392377f))))))));
}

// Full sync-word sign patterns: preamble (16 syms) + UW (12 syms),
// each symbol mapped to BPSK ±(1+j) on the +1+j / -1-j axis.
//
// Per gr-iridium burst_downmix_impl.cc::generate_sync_word():
//   DL preamble = 16× s0 (= +(1+j))   → signs all +1
//   UL preamble = 8× (s1, s0)         → signs -1, +1, -1, +1, ...
//   DL UW = { s0, s1, s1, s1, s1, s0, s0, s0, s1, s0, s0, s1 }
//   UL UW = { s1, s1, s0, s0, s0, s1, s0, s0, s1, s0, s1, s1 }
// Full preamble + UW sync templates, matching gr-iridium's
// generate_sync_word() exactly. DL preamble is 16× constant +1
// (broad triangular autocorrelation); UL preamble alternates ±1
// (sharp BPSK autocorrelation). The triangular DL peak makes
// direction discrimination noisier than ideal on borderline SNR
// — a UW-only variant gives sharper peaks but DEVIATES from
// gr-iridium and produced mixed results in testing (slight gain
// on host, slight loss on P4). Reverted to preamble+UW for
// gr-iridium alignment.
static const int8_t SYNC_DL_SIGN[SYNC_LENGTH] = {
    +1,+1,+1,+1,+1,+1,+1,+1,+1,+1,+1,+1,+1,+1,+1,+1,   // preamble
    +1,-1,-1,-1,-1,+1,+1,+1,-1,+1,+1,-1                  // UW
};
static const int8_t SYNC_UL_SIGN[SYNC_LENGTH] = {
    -1,+1,-1,+1,-1,+1,-1,+1,-1,+1,-1,+1,-1,+1,-1,+1,   // preamble
    -1,-1,+1,+1,+1,-1,+1,+1,-1,+1,-1,-1                  // UW
};

// RRC pulse shape: β=0.4, 51 taps at 10 sps = 5.1 symbol periods.
// Matches gr-iridium's prototype exactly (51 taps, fs=250 kHz,
// fs_sym=25 kHz, β=0.4 — see iridium_extractor_flowgraph.py and
// the burst_downmix RRC FIR init).
#define RRC_BETA       0.4f
#define RRC_NTAPS      51
// gr-iridium's sync_word_padded length: each symbol is followed by
// (sps-1)=9 zeros, then the FINAL trailing 9 zeros are erased
// (burst_downmix_impl.cc:251-259). So the padded sync is
//   SYNC_LENGTH * sps - (sps - 1) = 28*10 - 9 = 271 samples.
// After valid-mode RC filtering, the reference is still 271 samples;
// the RC trailing tail past the last symbol (positions 271..295) is
// NOT generated by gr-iridium. Match that exactly — using a 280-
// sample reference puts 9 extra RC-tail samples that bias the
// matched-filter peak position vs gr-iridium.
#define SYNC_RRC_LEN   (SYNC_LENGTH * SYM_STRIDE - (SYM_STRIDE - 1))  // 271 at sps=10

// Q14 fixed-point: tap range [-16384, +16383], multiply-accumulate
// over 51 taps fits in int32 with one bit of headroom. Output =
// (acc >> 14) saturated to int16. Q14 not Q15 because some RRC
// taps approach unity and Q15(1.0) = 32768 doesn't fit in int16.
#include "q14_fixed.h"

#ifdef ESP_PLATFORM
#include "dsps_fir.h"
#include "esp_heap_caps.h"
// D13 start-finder LP filter PIE state. Padded to 184 taps for the
// `coeffs_len % 8 == 0` PIE gate; the +1 zero is at array index [0]
// (= late end of the impulse response after dsps_fird's reversal),
// giving a clean 91-sample group delay we compensate by feeding 91
// trailing zeros and using outputs[91..91+search_max-1].
//
// Task #75 tested (and rejected): putting these in TCM via
// SPM_DRAM_ATTR (.spm.data at 0x30100000) caused the PIE FIR to
// double in time (first_decode 38.6 -> 77.6 ms/burst) and recall
// crashed from 93.8% to 53.8%. The PIE asm cannot read TCM
// efficiently. Coefficients must stay in regular DRAM (.bss) where
// the PIE vld.128 instructions work correctly.
static int16_t s_start_lp_taps_padded[/*START_LP_NTAPS_PADDED*/ 184]
    __attribute__((aligned(16)));
static fir_s16_t s_start_lp_fir;
static int s_start_lp_fir_inited = 0;
// Pad RRC taps from 51 to 56 (multiple of 8) for dsps_fird_s16_arp4.
// The PIE asm has an early `andi t2, t2, 7; beqz; j ansi` gate that
// falls back to the scalar ANSI variant unless coeffs_len % 8 == 0.
// The five zero taps are placed at the LATE end of the impulse
// response (dsps_fird's time-reversal makes them array indices [0..4],
// see uw_correlator_apply_rrc). Group delay is exactly 25 samples
// (= (RRC_NTAPS-1)/2), compensated at the call site by feeding 25
// trailing zeros and using outputs[25..25+n-1].
#define RRC_NTAPS_PADDED  56
#endif

#ifdef UW_CORRELATOR_CFO_DEBUG
#include <stdio.h>
#endif

// Q14 burst-side FIR taps (RRC). Used by uw_correlator_apply_rrc.
static int16_t s_rrc_taps_q14[RRC_NTAPS];

#ifdef ESP_PLATFORM
// Task #75 attempted SPM_DRAM_ATTR here -- caused PIE FIR slowdown.
// PIE asm reads TCM ineffectively; coefficients must stay in DRAM .bss.
static int16_t s_rrc_taps_padded[RRC_NTAPS_PADDED] __attribute__((aligned(16)));
static fir_s16_t s_rrc_fir_i, s_rrc_fir_q;
static int16_t *s_rrc_scr_in_i  = NULL;   // INTERNAL preferred, lazy;
static int16_t *s_rrc_scr_in_q  = NULL;   // falls back to PSRAM if internal heap
static int16_t *s_rrc_scr_out_i = NULL;   // is exhausted (multi-frame bursts).
static int16_t *s_rrc_scr_out_q = NULL;   // PIE asm only engages on internal.
static int      s_rrc_scr_cap   = 0;       // current capacity (complex samples)
static int      s_rrc_fir_inited = 0;
#endif

// RC-shaped sync word references in FLOAT (used by FFT correlation
// and CFO FFT paths, which are still float — Q15 FFT conversion
// tracked as the next step after this commit).
static float s_sync_dl_re[SYNC_RRC_LEN];
static float s_sync_dl_im[SYNC_RRC_LEN];
static float s_sync_ul_re[SYNC_RRC_LEN];
static float s_sync_ul_im[SYNC_RRC_LEN];
static float s_rrc_taps[RRC_NTAPS];     // float copy (used by init only)
static float s_rc_taps[RRC_NTAPS];      // float copy (used by init only)
static bool  s_sync_inited = false;

// Generate root-raised-cosine FIR taps. Standard textbook formula;
// matches gr::filter::firdes::root_raised_cosine. Used to RRC-filter
// the received burst (matched-filter side: gr-iridium's d_rrc_fir).
static void make_rrc_taps(float *taps, int ntaps, int sps, float beta)
{
    const float PI = 3.14159265358979323846f;
    int center = (ntaps - 1) / 2;
    float sum = 0.0f;
    for (int n = 0; n < ntaps; n++) {
        float k = (float)(n - center) / (float)sps;     // in symbol periods
        float v;
        float abs_k = k < 0 ? -k : k;
        if (abs_k < 1e-6f) {
            v = 1.0f - beta + 4.0f * beta / PI;
        } else {
            float four_bk = 4.0f * beta * k;
            float denom = PI * k * (1.0f - four_bk * four_bk);
            if (fabsf(denom) < 1e-9f) {
                // Singularity at k = ±1/(4β): use l'Hôpital limit.
                v = (beta / sqrtf(2.0f)) *
                    ((1.0f + 2.0f / PI) * sinf(PI / (4.0f * beta)) +
                     (1.0f - 2.0f / PI) * cosf(PI / (4.0f * beta)));
            } else {
                float num = sinf(PI * (1.0f - beta) * k)
                          + four_bk * cosf(PI * (1.0f + beta) * k);
                v = num / denom;
            }
        }
        taps[n] = v;
        sum += v;
    }
    // Normalise to unit DC gain (matches gr-iridium gain=1.0).
    if (sum != 0.0f) {
        float inv = 1.0f / sum;
        for (int n = 0; n < ntaps; n++) taps[n] *= inv;
    }
}

// Generate raised-cosine FIR taps. RC = RRC ⊛ RRC; gr-iridium uses
// RC on the sync_word reference so that correlating against the
// RRC-filtered burst gives the true matched-filter output.
static void make_rc_taps(float *taps, int ntaps, int sps, float beta)
{
    const float PI = 3.14159265358979323846f;
    int center = (ntaps - 1) / 2;
    float sum = 0.0f;
    for (int n = 0; n < ntaps; n++) {
        float k = (float)(n - center) / (float)sps;     // in symbol periods
        float v;
        float abs_k = k < 0 ? -k : k;
        if (abs_k < 1e-6f) {
            v = 1.0f;
        } else {
            float two_bk = 2.0f * beta * k;
            float denom = 1.0f - two_bk * two_bk;
            if (fabsf(denom) < 1e-9f) {
                // Singularity at k = ±1/(2β)
                v = (PI / 4.0f) * (sinf(PI / (2.0f * beta)) / (PI / (2.0f * beta)));
            } else {
                float sinc = (fabsf(PI * k) < 1e-9f) ? 1.0f
                             : sinf(PI * k) / (PI * k);
                v = sinc * cosf(PI * beta * k) / denom;
            }
        }
        taps[n] = v;
        sum += v;
    }
    if (sum != 0.0f) {
        float inv = 1.0f / sum;
        for (int n = 0; n < ntaps; n++) taps[n] *= inv;
    }
}

// Convolve the BPSK sync impulses (one per symbol, at stride sps)
// with the given pulse-shape FIR to get the matched-filter reference
// at sample rate. Output is complex (±1±j axis): for each symbol with
// sign s, the impulse contributes s·(1+j)·shape[k]. gr-iridium uses
// RC (= RRC ⊛ RRC) on the sync reference so that correlating against
// the RRC-filtered burst gives the optimal matched filter output.
static void build_shaped_sync(const int8_t *signs, const float *shape,
                              float *out_re, float *out_im)
{
    memset(out_re, 0, SYNC_RRC_LEN * sizeof(float));
    memset(out_im, 0, SYNC_RRC_LEN * sizeof(float));
    int center = (RRC_NTAPS - 1) / 2;
    for (int sym = 0; sym < SYNC_LENGTH; sym++) {
        int impulse_pos = sym * SYM_STRIDE;
        int s = signs[sym];                 // ±1
        for (int t = 0; t < RRC_NTAPS; t++) {
            int out_idx = impulse_pos + (t - center);
            if (out_idx < 0 || out_idx >= SYNC_RRC_LEN) continue;
            float contrib = (float)s * shape[t];
            out_re[out_idx] += contrib;
            out_im[out_idx] += contrib;
        }
    }
}

// FFT-based correlation (gr-iridium burst_downmix_impl.cc, lines
// 342-394, 608-650). The reversed-conjugated RC-shaped sync word
// is FFT'd once at init and stored in s_sync_dl_fft / s_sync_ul_fft.
// Per burst we FFT the burst (zero-padded to CORR_FFT_N), multiply
// elementwise by the stored sync FFT, IFFT, and peak-find.
//
// CORR_FFT_N matches gr-iridium's d_corr_fft_size at 10 sps. gri:
//   d_sync_search_len = (PREAMBLE_LENGTH_LONG + UW_LENGTH + 8) * 10
//                     = (64 + 12 + 8) * 10 = 840
//   sync_word_len     = 28 * 10 = 280
//   d_corr_fft_size   = next_pow2(840 + 280 - 1) = next_pow2(1119) = 2048
//
// BUG fixed May 2026: this was 1024, computed using PREAMBLE_LENGTH_SHORT
// instead of _LONG. With CORR_FFT_N < required, the FFT-based linear
// convolution aliases — the burst's data portion (samples ~280..1024)
// wraps into the front and creates spurious correlation peaks in
// the data region. On the ALBQ fixture this put the matched-filter
// peak ~500 samples (50 symbols) past the real sync position, with
// SNR just above the 6 dB threshold so the result still gets used.
// Downstream pre-rotation then aligned to the wrong location and
// qpsk_demod saw noise.
#define CORR_FFT_N   2048
#define CORR_FFT_LOG 11

// Matched-filter precision selector.
//   0 → Q15 BFP path (legacy, P4-friendly; kept for the embedded build)
//   1 → float32 path (mirrors gr-iridium's volk_32fc_*_32fc chain;
//        used to diagnose Q15 BFP precision loss as a source of
//        peak-position divergence vs gr-iridium)
//
// On the host we default to float to match gr-iridium exactly. On the
// P4 build we keep Q15 (cheaper, no scalar FPU pressure during the
// matched filter). Final P4 path is decided after the audit and
// measurement under Phase 3.6.P.
#ifndef CORR_USE_FLOAT_FFT
#define CORR_USE_FLOAT_FFT 1
#endif

// Read-only-after-init FFT precompute tables. Closed-form
// (bit-reversal + cosf/sinf twiddles + Blackman windows) so they're
// codegenned by tests/scripts/gen_uw_correlator_tables.py into
// uw_correlator_tables.c as `const`, landing in .rodata (flash).
// L2 cache covers the sequential FFT-inner-loop access pattern.
// Frees ~37 KiB from .ext_ram.bss (PSRAM) and 0 KiB from internal
// SRAM -- net: PSRAM heap grows by 37 KiB, flash binary grows by
// 37 KiB. Regenerate if CORR_FFT_N / CFO_FFT_N / CFO_INPUT_N /
// CFO_UW_ONLY_N change.
extern const uint16_t s_corr_brev[CORR_FFT_N];        // shared between Q15 and float FFT paths
#if !CORR_USE_FLOAT_FFT
static int16_t  s_corr_tw_re[CORR_FFT_N / 2];   // Q15 cos
static int16_t  s_corr_tw_im[CORR_FFT_N / 2];   // Q15 sin
// Pre-computed FFTs of the reversed-conjugated RC-shaped sync
// references, zero-padded to CORR_FFT_N. Used by the burst-
// correlation FFT path. gr-iridium pattern: `volk_32fc_conjugate`
// + `std::reverse` + FFT, stored as `d_dl_preamble_reversed_conj_fft`.
// Stored as int32 to match the radix2_fft_q15 internal precision
// (no per-stage shifting). Memory: 4 × CORR_FFT_N × 4B = 16 KB.
static int32_t  s_sync_dl_fft_re[CORR_FFT_N];
static int32_t  s_sync_dl_fft_im[CORR_FFT_N];
static int32_t  s_sync_ul_fft_re[CORR_FFT_N];
static int32_t  s_sync_ul_fft_im[CORR_FFT_N];
#endif

#if CORR_USE_FLOAT_FFT
// Parallel float-precision matched filter state. Twiddles built at
// init time; sync FFTs computed from the same s_sync_*_re/im sources
// but kept in float32. Memory: 4 × CORR_FFT_N × 4B = 32 KB.
extern const float               s_corr_tw_re_f[CORR_FFT_N / 2]; // generated
extern const float               s_corr_tw_im_f[CORR_FFT_N / 2]; // generated
// Sync FFTs depend on the runtime-built RC-shaped sync, so they
// can't be codegened without a much heavier Python step that
// duplicates the RRC + FFT chain. Left in PSRAM via
// EXT_RAM_BSS_ATTR. Sequential read pattern in the matched-filter
// inner loop is cache-friendly.
// Pre-computed reversed-conjugate sync FFTs. 4 * 8 KiB = 32 KiB,
// read once per spectrum-multiply loop (2 per uw_correlator_find call,
// ~6.6 reads per burst with the multi-frame loop). Held in INTERNAL
// SRAM: PSRAM round-trips here were a measurable chunk of the 16 ms/
// call UW cost (multi-frame fires uw_correlator_find ~3.3x per burst).
static float s_sync_dl_fft_re_f[CORR_FFT_N] __attribute__((aligned(16)));
static float s_sync_dl_fft_im_f[CORR_FFT_N] __attribute__((aligned(16)));
static float s_sync_ul_fft_re_f[CORR_FFT_N] __attribute__((aligned(16)));
static float s_sync_ul_fft_im_f[CORR_FFT_N] __attribute__((aligned(16)));
#endif

// Block-floating-point Q15 radix-2 DIT FFT. Buffers are int32 to
// allow growth between stages without truncation; after each stage
// the max magnitude is checked and the whole buffer right-shifted
// just enough to keep values bounded. The shift count is returned
// as `exp_shift` — the true value of bin k is buf[k] × 2^exp_shift.
//
// For peak-finding within a single FFT, exp_shift cancels out (all
// bins share it). For comparing two FFT outputs (e.g. the matched
// filter's burst × sync product), the caller adds the exponents.
//
// Typical case: sparse burst input (280 samples in 1024-pt buffer)
// barely grows per stage, so only a handful of shifts are needed
// and precision stays at ~14 bits. Worst case (DC input) shifts
// every stage, behaving like the standard per-stage-shift FFT.
static int radix2_fft_q15(int32_t *re, int32_t *im, int N, int log_N,
                           const uint16_t *brev,
                           const int16_t *tw_re, const int16_t *tw_im)
{
    for (int i = 0; i < N; i++) {
        int j = brev[i];
        if (j > i) {
            int32_t tr = re[i]; re[i] = re[j]; re[j] = tr;
            int32_t ti = im[i]; im[i] = im[j]; im[j] = ti;
        }
    }
    (void)log_N;
    int exp_shift = 0;
    for (int stride = 1; stride < N; stride <<= 1) {
        // Block-float: scan for max abs, shift down if approaching
        // the int32 ceiling. We pick threshold 2^28 so the next
        // stage's worst-case 2× growth (→ 2^29) stays well below
        // INT32_MAX (2^31).
        int32_t max_abs = 0;
        for (int i = 0; i < N; i++) {
            int32_t v = re[i]; if (v < 0) v = -v; if (v > max_abs) max_abs = v;
            v = im[i];          if (v < 0) v = -v; if (v > max_abs) max_abs = v;
        }
        int shift_now = 0;
        while (max_abs > (1 << 28)) { max_abs >>= 1; shift_now++; }
        if (shift_now) {
            for (int i = 0; i < N; i++) {
                re[i] >>= shift_now;
                im[i] >>= shift_now;
            }
            exp_shift += shift_now;
        }
        int span = stride << 1;
        int step = (N / 2) / stride;
        for (int k = 0; k < stride; k++) {
            int64_t wr = (int64_t)tw_re[k * step];
            int64_t wi = (int64_t)tw_im[k * step];
            for (int i = k; i < N; i += span) {
                int64_t xr = (int64_t)re[i + stride];
                int64_t xi = (int64_t)im[i + stride];
                int32_t tr = (int32_t)((wr * xr - wi * xi) >> 15);
                int32_t ti = (int32_t)((wr * xi + wi * xr) >> 15);
                re[i + stride] = re[i] - tr;
                im[i + stride] = im[i] - ti;
                re[i]          = re[i] + tr;
                im[i]          = im[i] + ti;
            }
        }
    }
    return exp_shift;
}

// Inverse FFT via conjugate-FFT-conjugate. Returns the cumulative
// shift exponent (same convention as radix2_fft_q15).
static int radix2_ifft_q15(int32_t *re, int32_t *im, int N, int log_N,
                            const uint16_t *brev,
                            const int16_t *tw_re, const int16_t *tw_im)
{
    for (int i = 0; i < N; i++) im[i] = -im[i];
    int e = radix2_fft_q15(re, im, N, log_N, brev, tw_re, tw_im);
    for (int i = 0; i < N; i++) im[i] = -im[i];
    return e;
}

#if CORR_USE_FLOAT_FFT

// Diagnostic counters at file scope, visible to both host and target.
// Timer updates inside #if defined(ESP_PLATFORM) (esp_timer isn't on
// host); counters stay 0 there. Smoke-test consumer reads them on
// target only.
volatile uint64_t g_pie_fft_inner_us = 0;   // FFT + bit-rev (target only)
volatile uint64_t g_pie_fft_outer_us = 0;   // interleave + de-interleave
volatile uint32_t g_pie_fft_calls    = 0;
volatile uint64_t g_uw_specmul_us    = 0;
volatile uint64_t g_uw_magsearch_us  = 0;
// Pre-UW CFO peak-confidence counter (#115): cfo_fine_estimate returned
// 0 because the squared-FFT peak wasn't ≥ 6 dB above the second-best
// peak outside its main lobe. Healthy bursts should rarely trigger;
// elevated rate = noise dominating the pre-UW window.
static volatile uint32_t s_cfo_low_confidence_count = 0;
uint32_t uw_correlator_get_cfo_low_confidence_count(void) {
    return s_cfo_low_confidence_count;
}

#if defined(ESP_PLATFORM)
// Task #58/#67: PIE float FFT wrapper. Replaces ~3× radix2_fft_f32 calls
// per uw_correlator_find with esp-dsp's dsps_fft2r_fc32_arp4 (8-lane
// SIMD), saving ~10 ms/burst on the matched-filter hot path.
//
// PIE FFT requires:
//   - input/output buffer in INTERNAL SRAM (esp.vld.128.ip can't service
//     PSRAM access timing -- output is garbage if buffer is in PSRAM)
//   - interleaved IQ float format (caller's re[]/im[] are de-interleaved)
//   - dsps_bit_rev_fc32_ansi call AFTER the FFT to un-reverse output
//
// Wrapper: lazy-alloc 16 KB internal-SRAM scratch + 4 KB PIE twiddle
// table. Interleave re[]/im[] in, run FFT + bit-rev, de-interleave out.
// 60 us copy overhead vs ~13 ms FFT savings per call.
//
// Bit-equivalence vs scalar radix2_fft_f32 verified by the diff harness
// in pie_fft_diff_test.c (task #67): all peak bins match, max abs diff
// ~1e-4 worst case, impulse case bit-exact at 0.0.
#include "dsps_fft2r.h"
#include "esp_heap_caps.h"
#include "esp_timer.h"
static float *s_pie_fft_scratch = NULL;   // 2*CORR_FFT_N floats interleaved IQ
static float *s_pie_fft_w_table = NULL;   // 1*CORR_FFT_N floats twiddle table
static bool   s_pie_fft_inited  = false;

static void pie_fft_fc32_init(void)
{
    if (s_pie_fft_inited) return;
    s_pie_fft_scratch = (float *)heap_caps_aligned_alloc(
                            16, 2 * CORR_FFT_N * sizeof(float),
                            MALLOC_CAP_INTERNAL);
    s_pie_fft_w_table = (float *)heap_caps_aligned_alloc(
                            16, CORR_FFT_N * sizeof(float),
                            MALLOC_CAP_INTERNAL);
    if (!s_pie_fft_scratch || !s_pie_fft_w_table) return;
    if (dsps_fft2r_init_fc32(s_pie_fft_w_table, CORR_FFT_N) != ESP_OK) return;
    s_pie_fft_inited = true;
}

// In-place float FFT on de-interleaved re[]/im[] arrays.
static void pie_fft_fc32_2048(float *re, float *im)
{
    if (!s_pie_fft_inited) pie_fft_fc32_init();
    if (!s_pie_fft_inited) return;   // alloc failed -> no-op (will mis-decode)

    int64_t t0 = esp_timer_get_time();
    // Interleave re/im into internal-SRAM scratch.
    for (int i = 0; i < CORR_FFT_N; i++) {
        s_pie_fft_scratch[2 * i + 0] = re[i];
        s_pie_fft_scratch[2 * i + 1] = im[i];
    }
    int64_t t1 = esp_timer_get_time();
    dsps_fft2r_fc32_arp4(s_pie_fft_scratch, CORR_FFT_N);
    dsps_bit_rev_fc32_ansi(s_pie_fft_scratch, CORR_FFT_N);
    int64_t t2 = esp_timer_get_time();
    // De-interleave back to caller's arrays.
    for (int i = 0; i < CORR_FFT_N; i++) {
        re[i] = s_pie_fft_scratch[2 * i + 0];
        im[i] = s_pie_fft_scratch[2 * i + 1];
    }
    int64_t t3 = esp_timer_get_time();
    g_pie_fft_outer_us += (uint64_t)((t1 - t0) + (t3 - t2));
    g_pie_fft_inner_us += (uint64_t)(t2 - t1);
    g_pie_fft_calls    += 1;
}

// IFFT via conjugate-FFT-conjugate. gri convention: no 1/N scaling
// (matched-filter peak finder operates on magnitude² and absorbs the
// constant scale).
static void pie_ifft_fc32_2048(float *re, float *im)
{
    for (int i = 0; i < CORR_FFT_N; i++) im[i] = -im[i];
    pie_fft_fc32_2048(re, im);
    for (int i = 0; i < CORR_FFT_N; i++) im[i] = -im[i];
}
#endif // ESP_PLATFORM

// Generic float radix-2 DIT FFT. Same butterfly structure as
// cfo_fft_f32 but parameterised by N — used by both the CFO path
// (N=4096) and the matched-filter path (N=2048) when running the
// float-precision build.
static void radix2_fft_f32(float *re, float *im, int N, int log_N,
                            const uint16_t *brev,
                            const float *tw_re, const float *tw_im)
{
    (void)log_N;
    for (int i = 0; i < N; i++) {
        int j = brev[i];
        if (j > i) {
            float tr = re[i]; re[i] = re[j]; re[j] = tr;
            float ti = im[i]; im[i] = im[j]; im[j] = ti;
        }
    }
    for (int stride = 1; stride < N; stride <<= 1) {
        int span = stride << 1;
        int step = (N / 2) / stride;
        for (int k = 0; k < stride; k++) {
            float wr = tw_re[k * step];
            float wi = tw_im[k * step];
            for (int i = k; i < N; i += span) {
                float xr = re[i + stride];
                float xi = im[i + stride];
                float tr = wr * xr - wi * xi;
                float ti = wr * xi + wi * xr;
                re[i + stride] = re[i] - tr;
                im[i + stride] = im[i] - ti;
                re[i]          = re[i] + tr;
                im[i]          = im[i] + ti;
            }
        }
    }
}

static void radix2_ifft_f32(float *re, float *im, int N, int log_N,
                             const uint16_t *brev,
                             const float *tw_re, const float *tw_im)
{
    for (int i = 0; i < N; i++) im[i] = -im[i];
    radix2_fft_f32(re, im, N, log_N, brev, tw_re, tw_im);
    for (int i = 0; i < N; i++) im[i] = -im[i];
    // gr-iridium's IFFT (volk fft_complex_rev) does NOT divide by N —
    // they rely on the FFT/IFFT pair being conjugate-symmetric in
    // magnitude. We omit the /N for the same reason (the peak finder
    // operates on magnitude², so any constant scale cancels out).
}
#endif

static void sync_init(void)
{
    if (s_sync_inited) return;
    make_rrc_taps(s_rrc_taps, RRC_NTAPS, SYM_STRIDE, RRC_BETA);
    make_rc_taps (s_rc_taps,  RRC_NTAPS, SYM_STRIDE, RRC_BETA);
    build_shaped_sync(SYNC_DL_SIGN, s_rc_taps, s_sync_dl_re, s_sync_dl_im);
    build_shaped_sync(SYNC_UL_SIGN, s_rc_taps, s_sync_ul_re, s_sync_ul_im);
    // Quantise to Q14: tap × Q14_ONE = Q14 representation. Since the
    // float taps are DC-gain-normalised (sum = 1), the Q14 taps' DC
    // gain is also 1 — output = sum(tap_q14[n] × x[n]) >> Q14_SHIFT
    // ≈ float convolution result. Max float tap ≈ 0.1 → Q14 ≈ 1638,
    // comfortably in int16 range.
    for (int n = 0; n < RRC_NTAPS; n++) {
        float v = s_rrc_taps[n] * (float)Q14_ONE;
        if (v > (float)INT16_MAX) v = (float)INT16_MAX;
        if (v < (float)INT16_MIN) v = (float)INT16_MIN;
        s_rrc_taps_q14[n] = (int16_t)lrintf(v);
    }

    // Correlation FFT bit-reversal + float twiddles are codegenned
    // const in uw_correlator_tables.c. The Q15 twiddle path remains
    // runtime-initialised (off by default; CORR_USE_FLOAT_FFT=1).
#if !CORR_USE_FLOAT_FFT
    for (int k = 0; k < CORR_FFT_N / 2; k++) {
        double ang = -2.0 * 3.14159265358979323846 * (double)k / (double)CORR_FFT_N;
        s_corr_tw_re[k] = (int16_t)lrintf((float)cos(ang) * (float)INT16_MAX);
        s_corr_tw_im[k] = (int16_t)lrintf((float)sin(ang) * (float)INT16_MAX);
    }
#endif

    const int L = SYNC_RRC_LEN;
#if !CORR_USE_FLOAT_FFT
    // Pre-compute reversed-conjugated sync FFTs. gr-iridium does:
    //   std::reverse(sync_padded.begin(), sync_padded.end());
    //   volk_32fc_conjugate_32fc(sync_padded, sync_padded, ...);
    //   fft_engine.execute(sync_padded → store_buf)
    // For our purposes, the RC-shaped sync is real-imag (1+j axis),
    // so reversed-conjugate is: out[n] = conj(sync[L-1-n]).
    //
    // Quantise sync ref to int16 (raw, range up to ±INT16_MAX since
    // s_sync_*_re/im are in [-1, 1]). FFT into int32 storage so the
    // full dynamic range is preserved across all stages. After FFT
    // we renormalise both DL and UL sync FFTs to a common max
    // magnitude — otherwise the BFP FFT's per-FFT exp_shift would
    // differ between DL (has a strong DC bin from the all-positive
    // preamble) and UL (alternating preamble, near-zero DC),
    // breaking the peak_DL vs peak_UL discrimination in the matched
    // filter.
    static int32_t tmp_re[CORR_FFT_N], tmp_im[CORR_FFT_N];
    // Target magnitude after sync FFT renormalisation: 2^24 leaves
    // 7 bits of headroom for the burst×sync multiply (burst FFT max
    // ~ 2^21, product ~ 2^45, >>15 = 2^30 — fits int32 with margin).
    const int32_t SYNC_TARGET_MAX = 1 << 24;
    // DL
    memset(tmp_re, 0, sizeof(tmp_re));
    memset(tmp_im, 0, sizeof(tmp_im));
    for (int n = 0; n < L; n++) {
        float r =  s_sync_dl_re[L - 1 - n];
        float i = -s_sync_dl_im[L - 1 - n];      // conjugate
        tmp_re[n] = (int32_t)lrintf(r * (float)INT16_MAX);
        tmp_im[n] = (int32_t)lrintf(i * (float)INT16_MAX);
    }
    (void)radix2_fft_q15(tmp_re, tmp_im, CORR_FFT_N, CORR_FFT_LOG,
                          s_corr_brev, s_corr_tw_re, s_corr_tw_im);
    {
        int32_t max_abs = 0;
        for (int k = 0; k < CORR_FFT_N; k++) {
            int32_t v = tmp_re[k]; if (v < 0) v = -v; if (v > max_abs) max_abs = v;
            v = tmp_im[k];          if (v < 0) v = -v; if (v > max_abs) max_abs = v;
        }
        if (max_abs > 0) {
            int64_t scale = ((int64_t)SYNC_TARGET_MAX << 15) / (int64_t)max_abs;
            for (int k = 0; k < CORR_FFT_N; k++) {
                tmp_re[k] = (int32_t)(((int64_t)tmp_re[k] * scale) >> 15);
                tmp_im[k] = (int32_t)(((int64_t)tmp_im[k] * scale) >> 15);
            }
        }
    }
    memcpy(s_sync_dl_fft_re, tmp_re, sizeof(tmp_re));
    memcpy(s_sync_dl_fft_im, tmp_im, sizeof(tmp_im));
    // UL
    memset(tmp_re, 0, sizeof(tmp_re));
    memset(tmp_im, 0, sizeof(tmp_im));
    for (int n = 0; n < L; n++) {
        float r =  s_sync_ul_re[L - 1 - n];
        float i = -s_sync_ul_im[L - 1 - n];
        tmp_re[n] = (int32_t)lrintf(r * (float)INT16_MAX);
        tmp_im[n] = (int32_t)lrintf(i * (float)INT16_MAX);
    }
    (void)radix2_fft_q15(tmp_re, tmp_im, CORR_FFT_N, CORR_FFT_LOG,
                          s_corr_brev, s_corr_tw_re, s_corr_tw_im);
    {
        int32_t max_abs = 0;
        for (int k = 0; k < CORR_FFT_N; k++) {
            int32_t v = tmp_re[k]; if (v < 0) v = -v; if (v > max_abs) max_abs = v;
            v = tmp_im[k];          if (v < 0) v = -v; if (v > max_abs) max_abs = v;
        }
        if (max_abs > 0) {
            int64_t scale = ((int64_t)SYNC_TARGET_MAX << 15) / (int64_t)max_abs;
            for (int k = 0; k < CORR_FFT_N; k++) {
                tmp_re[k] = (int32_t)(((int64_t)tmp_re[k] * scale) >> 15);
                tmp_im[k] = (int32_t)(((int64_t)tmp_im[k] * scale) >> 15);
            }
        }
    }
    memcpy(s_sync_ul_fft_re, tmp_re, sizeof(tmp_re));
    memcpy(s_sync_ul_fft_im, tmp_im, sizeof(tmp_im));
#endif  // !CORR_USE_FLOAT_FFT (Q15 sync FFT precompute)

#if CORR_USE_FLOAT_FFT
    // Float-precision sync FFTs — mirror gr-iridium exactly:
    //   reversed + conjugated sync (in float, no quantisation),
    //   zero-padded into a CORR_FFT_N buffer, forward FFT, stored
    //   verbatim. No SYNC_TARGET_MAX renormalisation (the Q15 BFP
    //   path's renorm has no gri equivalent and is potentially
    //   biasing peak position; the float path skips it).
    {
        // Init-time scratch -- runs once per program. PSRAM placement
        // costs nothing here. See docs/p4-bss-audit.md win #2.
        static EXT_RAM_BSS_ATTR float ftmp_re[CORR_FFT_N], ftmp_im[CORR_FFT_N];
        // DL
        memset(ftmp_re, 0, sizeof(ftmp_re));
        memset(ftmp_im, 0, sizeof(ftmp_im));
        for (int n = 0; n < L; n++) {
            ftmp_re[n] =  s_sync_dl_re[L - 1 - n];
            ftmp_im[n] = -s_sync_dl_im[L - 1 - n];   // conjugate
        }
        radix2_fft_f32(ftmp_re, ftmp_im, CORR_FFT_N, CORR_FFT_LOG,
                       s_corr_brev, s_corr_tw_re_f, s_corr_tw_im_f);
        memcpy(s_sync_dl_fft_re_f, ftmp_re, sizeof(ftmp_re));
        memcpy(s_sync_dl_fft_im_f, ftmp_im, sizeof(ftmp_im));
        // UL
        memset(ftmp_re, 0, sizeof(ftmp_re));
        memset(ftmp_im, 0, sizeof(ftmp_im));
        for (int n = 0; n < L; n++) {
            ftmp_re[n] =  s_sync_ul_re[L - 1 - n];
            ftmp_im[n] = -s_sync_ul_im[L - 1 - n];
        }
        radix2_fft_f32(ftmp_re, ftmp_im, CORR_FFT_N, CORR_FFT_LOG,
                       s_corr_brev, s_corr_tw_re_f, s_corr_tw_im_f);
        memcpy(s_sync_ul_fft_re_f, ftmp_re, sizeof(ftmp_re));
        memcpy(s_sync_ul_fft_im_f, ftmp_im, sizeof(ftmp_im));
    }
#endif

    s_sync_inited = true;
}

// gr-iridium-style fine CFO estimator. Squaring a BPSK signal
// (UW symbols at quadrants 0/2 = ±(1+j)) removes the modulation:
//   x² = (±(1+j))² = ±2j → constant ±2j, no information, so any
//   carrier offset Δω becomes a tone at 2Δω after squaring.
// We FFT the squared region, find the peak, parabolic-interpolate
// for sub-bin resolution, divide by 2 to undo squaring. Result is
// returned in rad/sym (assuming the input samples are at 2 sps,
// which matches the rest of this module).
//
// N=64 with hand-rolled radix-2 to keep the call cost tiny — this
// runs once per detected burst, so a few hundred flops is nothing.
// gr-iridium parameters (burst_downmix_impl.cc lines 128-134):
//   d_cfo_est_fft_size = next_pow2(sps × (PREAMBLE_LENGTH_SHORT + 10))
//                      = next_pow2(10 × 26) = 512  (at 10 sps)
//   d_fft_over_size_facor = 16  → effective FFT = 512 × 16 = 8192
//   Window = Blackman (gr::fft::window::WIN_BLACKMAN)
//   No SNR gate.
// We use a 4096-pt FFT (still gives ~60 Hz resolution at 250 kHz =
// ~0.015 rad/sym, plenty for our needs) — keeps memory bounded.
#define CFO_FFT_N        4096
#define CFO_FFT_LOG      12
// gr-iridium burst_downmix_impl.cc:128-131:
//   d_cfo_est_fft_size = pow(2, int(log(sps * (PREAMBLE_LENGTH_SHORT + 10))
//                                   / log(2)))
//                      = pow(2, int(log(260) / log(2)))  = 256
// i.e. (preamble + 10 UW symbols) rounded DOWN to next power of 2.
// We previously used SYNC_LENGTH*sps = 280, which changed both the
// Blackman window shape and the squared-signal spectral content vs
// gr-iridium — biasing the squared-FFT peak position on borderline
// bursts.
#define CFO_INPUT_N      256
#define CFO_PREAMBLE_N   (PREAMBLE_LENGTH * UW_SPS)    // 160 samples
#define CFO_UW_ONLY_N    (UW_LENGTH * UW_SPS)          // 120 samples (fallback)

// Select CFO FFT precision at compile-time. Default is float (matches
// gr-iridium's volk_32fc_*_32fc + fft_complex path exactly). Setting
// CFO_USE_Q15_FFT=1 switches to the legacy Q15 BFP path — lower
// precision but smaller scratch — useful for a future size-constrained
// build profile. The Q15 code below is preserved intact; the gate
// here ensures its storage (~38 KB of internal-SRAM .bss: tw_re/im,
// window_full/uw, plus the function-static re/im[CFO_FFT_N] inside
// cfo_fine_estimate_q15) is excluded from the binary when off.
#ifndef CFO_USE_Q15_FFT
#define CFO_USE_Q15_FFT 0
#endif

static inline float parabolic_interp(float yl, float yc, float yr);

extern const uint16_t s_cfo_brev[CFO_FFT_N]; // generated
#if CFO_USE_Q15_FFT
static int16_t  s_cfo_tw_re[CFO_FFT_N / 2];     // Q15 cos
static int16_t  s_cfo_tw_im[CFO_FFT_N / 2];     // Q15 sin
#endif
// Float twiddle factors for the CFO squared-FFT. The Q15 version
// above is kept compiled (cfo_init sets it) but the CFO function now
// uses float precision — gr-iridium uses float throughout the
// squared-FFT path and our previous Q15 BFP version was losing
// resolution at borderline SNR, picking noise peaks instead of the
// real carrier residual. Cost is ~32 KB scratch + ~16 KB twiddles
// in BSS, plus a few hundred microseconds per burst (acceptable —
// the CFO step runs once per detected burst).
extern const float               s_cfo_tw_re_f[CFO_FFT_N / 2];     // generated
extern const float               s_cfo_tw_im_f[CFO_FFT_N / 2];     // generated
extern const float               s_cfo_window_full_f[CFO_INPUT_N]; // generated
extern const float               s_cfo_window_uw_f[CFO_UW_ONLY_N]; // generated
// Blackman windows in Q15 (matches gr::fft::window::WIN_BLACKMAN):
//   w[n] = 0.42 - 0.5·cos(2πn/(N-1)) + 0.08·cos(4πn/(N-1))
// Window values are in [0, 1] → Q15 representation [0, INT16_MAX].
#if CFO_USE_Q15_FFT
static int16_t  s_cfo_window_full[CFO_INPUT_N];
static int16_t  s_cfo_window_uw[CFO_UW_ONLY_N];
#endif
static bool     s_cfo_inited = false;

static void cfo_init(void)
{
    if (s_cfo_inited) return;
    // CFO bit-reversal, float twiddles, and float Blackman windows
    // are codegenned const in uw_correlator_tables.c. The Q15
    // versions (off by default; CFO_USE_Q15_FFT=0) still need
    // runtime init.
#if CFO_USE_Q15_FFT
    for (int k = 0; k < CFO_FFT_N / 2; k++) {
        double ang = -2.0 * 3.14159265358979323846 * (double)k / (double)CFO_FFT_N;
        s_cfo_tw_re[k] = (int16_t)lrintf((float)cos(ang) * (float)INT16_MAX);
        s_cfo_tw_im[k] = (int16_t)lrintf((float)sin(ang) * (float)INT16_MAX);
    }
    const float PI = 3.14159265358979323846f;
    for (int i = 0; i < CFO_INPUT_N; i++) {
        float t = (float)i / (float)(CFO_INPUT_N - 1);
        float w = 0.42f - 0.5f * cosf(2.0f * PI * t)
                        + 0.08f * cosf(4.0f * PI * t);
        s_cfo_window_full[i] = (int16_t)lrintf(w * (float)INT16_MAX);
    }
    for (int i = 0; i < CFO_UW_ONLY_N; i++) {
        float t = (float)i / (float)(CFO_UW_ONLY_N - 1);
        float w = 0.42f - 0.5f * cosf(2.0f * PI * t)
                        + 0.08f * cosf(4.0f * PI * t);
        s_cfo_window_uw[i] = (int16_t)lrintf(w * (float)INT16_MAX);
    }
#endif
    s_cfo_inited = true;
}

#if CFO_USE_Q15_FFT
// Forward declaration so cfo_fine_estimate can dispatch to the Q15
// path when CFO_USE_Q15_FFT=1.
static float cfo_fine_estimate_q15(const int16_t *burst_2sps,
                                    int n_complex, int uw_offset_complex);
#endif

// Float 4096-pt radix-2 DIT FFT — same butterfly structure as
// cfo_fft_q15 below but with full float precision throughout. Used
// by cfo_fine_estimate to match gr-iridium's float-precision squared-
// FFT path (their volk_32fc_*_32fc + d_cfo_est_fft.execute()). The
// Q15 BFP version below is kept for the optional CFO_USE_Q15_FFT
// build path.
// Note on PIE FFT swap for CFO N=4096:
// esp-dsp's dsps_fft2r_init_fc32 is single-instance globally
// (`if (dsps_fft2r_initialized != 0) return;` at the top). The UW
// correlator already initialises it for N=2048; a second init for
// N=4096 is silently ignored and the FFT call would produce garbage.
// Sharing a single max-N twiddle table requires layout-aware indexing
// that doesn't match the bit-rev table esp-dsp builds at init time.
// Kept as scalar radix-2 DIT here; the internal-SRAM move above still
// helps the per-burst PSRAM stalls.
static void cfo_fft_f32(float *re, float *im)
{
    // Bit-reverse permute.
    for (int i = 0; i < CFO_FFT_N; i++) {
        int j = s_cfo_brev[i];
        if (j > i) {
            float tr = re[i]; re[i] = re[j]; re[j] = tr;
            float ti = im[i]; im[i] = im[j]; im[j] = ti;
        }
    }
    // Cooley-Tukey radix-2 DIT.
    for (int stride = 1; stride < CFO_FFT_N; stride <<= 1) {
        int span = stride << 1;
        int step = (CFO_FFT_N / 2) / stride;
        for (int k = 0; k < stride; k++) {
            float wr = s_cfo_tw_re_f[k * step];
            float wi = s_cfo_tw_im_f[k * step];
            for (int i = k; i < CFO_FFT_N; i += span) {
                float xr = re[i + stride];
                float xi = im[i + stride];
                float tr = wr * xr - wi * xi;
                float ti = wr * xi + wi * xr;
                re[i + stride] = re[i] - tr;
                im[i + stride] = im[i] - ti;
                re[i]          = re[i] + tr;
                im[i]          = im[i] + ti;
            }
        }
    }
}

#if CFO_USE_Q15_FFT
// Q15 4096-pt block-floating-point FFT (same scheme as radix2_fft_q15
// — int32 buffers, scan max before each stage, shift only as needed).
// Returns the cumulative shift exponent.
static int cfo_fft_q15(int32_t *re, int32_t *im)
{
    for (int i = 0; i < CFO_FFT_N; i++) {
        int j = s_cfo_brev[i];
        if (j > i) {
            int32_t tr = re[i]; re[i] = re[j]; re[j] = tr;
            int32_t ti = im[i]; im[i] = im[j]; im[j] = ti;
        }
    }
    int exp_shift = 0;
    for (int stride = 1; stride < CFO_FFT_N; stride <<= 1) {
        int32_t max_abs = 0;
        for (int i = 0; i < CFO_FFT_N; i++) {
            int32_t v = re[i]; if (v < 0) v = -v; if (v > max_abs) max_abs = v;
            v = im[i];          if (v < 0) v = -v; if (v > max_abs) max_abs = v;
        }
        int shift_now = 0;
        while (max_abs > (1 << 28)) { max_abs >>= 1; shift_now++; }
        if (shift_now) {
            for (int i = 0; i < CFO_FFT_N; i++) {
                re[i] >>= shift_now;
                im[i] >>= shift_now;
            }
            exp_shift += shift_now;
        }
        int span = stride << 1;
        int step = (CFO_FFT_N / 2) / stride;
        for (int k = 0; k < stride; k++) {
            int64_t wr = (int64_t)s_cfo_tw_re[k * step];
            int64_t wi = (int64_t)s_cfo_tw_im[k * step];
            for (int i = k; i < CFO_FFT_N; i += span) {
                int64_t xr = (int64_t)re[i + stride];
                int64_t xi = (int64_t)im[i + stride];
                int32_t tr = (int32_t)((wr * xr - wi * xi) >> 15);
                int32_t ti = (int32_t)((wr * xi + wi * xr) >> 15);
                re[i + stride] = re[i] - tr;
                im[i + stride] = im[i] - ti;
                re[i]          = re[i] + tr;
                im[i]          = im[i] + ti;
            }
        }
    }
    return exp_shift;
}
#endif  // CFO_USE_Q15_FFT (cfo_fft_q15)

// Square-then-FFT CFO estimator. Uses preamble + UW (~56 samples)
// when uw_offset is large enough to include the preamble; otherwise
// falls back to UW-only (24 samples). The Iridium preamble (DL: 16×
// (+1+j); UL: alternating (-1-j), (+1+j)) squares to a constant 2j
// phasor — both halves of the squared signal are noise-free DC, so
// the carrier offset becomes a single clean tone at Δω rad/sample
// throughout the whole window. Returns omega_per_sym in rad/sym
// (with the sign convention the worker expects, see end of function).
// Select CFO FFT precision at compile-time. Default is float to match
// gr-iridium's volk_32fc_*_32fc + fft_complex path exactly. Define
// CFO_USE_Q15_FFT=1 to use the legacy Q15 BFP path (lower precision
// but smaller scratch — useful for the eventual size-constrained
// build profile if we ever revisit). Both paths are kept compiled
// so the switch is a one-line change.
#ifndef CFO_USE_Q15_FFT
#define CFO_USE_Q15_FFT 0
#endif

static float cfo_fine_estimate(const int16_t *burst_2sps, int n_complex,
                                int uw_offset_complex)
{
    cfo_init();

#if CFO_USE_Q15_FFT
    return cfo_fine_estimate_q15(burst_2sps, n_complex, uw_offset_complex);
#endif

    // FFT scratch — float for the gr-iridium-aligned full-precision
    // path. Q15 BFP was losing peak-vs-noise resolution at borderline
    // SNR; float matches gr-iridium's volk_32fc_*_32fc + fft_complex
    // exactly. 32 KB scratch in INTERNAL SRAM: PIE FFT (via
    // pie_cfo_fft_fc32) requires its operands to live where it can
    // read them, and the magnitude search below benefits from the same
    // L2 hit-rate improvement we measured on UW (was PSRAM).
    static float re[CFO_FFT_N] __attribute__((aligned(16)));
    static float im[CFO_FFT_N] __attribute__((aligned(16)));
    memset(re, 0, sizeof(re));
    memset(im, 0, sizeof(im));

    // Decide preamble+UW vs UW-only based on what's in range.
    int start, n_in;
    const float *win;
    if (uw_offset_complex >= CFO_PREAMBLE_N &&
        uw_offset_complex - CFO_PREAMBLE_N + CFO_INPUT_N <= n_complex) {
        start = uw_offset_complex - CFO_PREAMBLE_N;
        n_in  = CFO_INPUT_N;
        win   = s_cfo_window_full_f;
    } else if (uw_offset_complex + CFO_UW_ONLY_N <= n_complex) {
        start = uw_offset_complex;
        n_in  = CFO_UW_ONLY_N;
        win   = s_cfo_window_uw_f;
    } else {
        return 0.0f;       // burst too short, skip
    }

    // Square the windowed region (float precision). (r + j·m)² =
    // (r²-m²) + j·(2·r·m). gr-iridium uses volk_32fc_s32f_power_32fc
    // then volk_32fc_32f_multiply_32fc — same math, same precision.
    // Input int16 values normalised to [-1, 1] before squaring keeps
    // the squared magnitudes in a reasonable range for the FFT.
    const float SCALE = 1.0f / 32768.0f;
    for (int i = 0; i < n_in; i++) {
        float r = (float)burst_2sps[(start + i) * 2 + 0] * SCALE;
        float m = (float)burst_2sps[(start + i) * 2 + 1] * SCALE;
        float sq_re = r * r - m * m;
        float sq_im = 2.0f * r * m;
        re[i] = sq_re * win[i];
        im[i] = sq_im * win[i];
    }

    cfo_fft_f32(re, im);

    // Find peak (gr-iridium: std::max_element on magnitude²,
    // burst_downmix_impl.cc:527-528). gr-iridium uses unbounded search
    // over all FFT bins — DO NOT add a search range here. If the
    // squared signal has noise peaks beating the preamble's DC tone,
    // the cause is upstream divergence in the windowed signal, not the
    // peak finder.
    //
    // Peak-confidence filter (#115): also track the second-best peak
    // outside the main lobe (±2 bins of the best). For a real preamble
    // tone, the squared-FFT peak is 30-50 dB above the noise floor; for
    // a noise-dominated input, the "peak" is only a few dB above other
    // noise bins. Returning a noise-driven CFO leads burst_pipeline to
    // mis-rotate the burst past the PLL's capture range. If the peak
    // isn't at least 4× (= 6 dB) above the second peak, return 0.0f —
    // the post-UW CFO refinement will then carry the load on its
    // anchored (preamble-only) window. Gain: 0.3-0.8 dB on borderline
    // bursts. Cost: <1 us extra arithmetic per CFO estimate.
    float peak_mag    = -1.0f;
    int   peak_k      = 0;
    float second_mag  = -1.0f;
    for (int k = 0; k < CFO_FFT_N; k++) {
        float rr = re[k], ii = im[k];
        float m = rr * rr + ii * ii;
        if (m > peak_mag) {
            // Demote previous best (if any) to the second-best candidate.
            // It must lie outside the main lobe — that check happens in
            // the next pass below.
            peak_mag = m; peak_k = k;
        }
    }
    if (peak_mag <= 0.0f) return 0.0f;
    // Second-best magnitude OUTSIDE the main lobe (±2 bins of peak_k,
    // mod CFO_FFT_N for wrap). Excluding the lobe avoids reporting the
    // peak's own sidelobe as the second peak.
    for (int k = 0; k < CFO_FFT_N; k++) {
        int dk = k - peak_k;
        if (dk < 0) dk = -dk;
        if (dk > CFO_FFT_N / 2) dk = CFO_FFT_N - dk;  // wrap distance
        if (dk <= 2) continue;
        float rr = re[k], ii = im[k];
        float m = rr * rr + ii * ii;
        if (m > second_mag) second_mag = m;
    }
    // Confidence test: require ≥ 6 dB (4×) peak-to-second-best ratio.
    // second_mag < 0 means there were < 5 valid bins, which shouldn't
    // happen at CFO_FFT_N >= 16 — but treat as untrusted.
    if (second_mag <= 0.0f || peak_mag < 4.0f * second_mag) {
        s_cfo_low_confidence_count++;
        return 0.0f;
    }

#ifdef UW_CORRELATOR_CFO_DEBUG
    {
        // Dump top 5 peaks (signed bin, omega rad/sym, magnitude).
        const int N = CFO_FFT_N;
        typedef struct { int k; float m; } pk_t;
        pk_t top[5];
        for (int i = 0; i < 5; i++) { top[i].k = 0; top[i].m = -1.0f; }
        for (int k = 0; k < N; k++) {
            float rr = re[k], ii = im[k];
            float m = rr * rr + ii * ii;
            for (int i = 0; i < 5; i++) {
                if (m > top[i].m) {
                    for (int j = 4; j > i; j--) top[j] = top[j-1];
                    top[i].k = k; top[i].m = m;
                    break;
                }
            }
        }
        fprintf(stderr, "[cfo] top peaks (n_in=%d, win=%s):", n_in,
                (win == s_cfo_window_full_f) ? "full" : "uw-only");
        for (int i = 0; i < 5; i++) {
            int kf_dbg = top[i].k;
            if (kf_dbg >= N/2) kf_dbg -= N;
            float omega_dbg = -2.0f * 3.14159265358979323846f * kf_dbg / (float)N
                              * ((float)UW_SPS / 2.0f);
            fprintf(stderr, "  k=%+5d ω=%+.3f m=%.2e",
                    kf_dbg, (double)omega_dbg, (double)top[i].m);
        }
        fprintf(stderr, "\n");
    }
#endif

    // Parabolic interpolation around the peak (with wrap).
    int km1 = (peak_k - 1 + CFO_FFT_N) % CFO_FFT_N;
    int kp1 = (peak_k + 1) % CFO_FFT_N;
    float yl = re[km1] * re[km1] + im[km1] * im[km1];
    float yc = peak_mag;
    float yr = re[kp1] * re[kp1] + im[kp1] * im[kp1];
    float delta = parabolic_interp(yl, yc, yr);

    // Convert (signed) bin position to rad/sym.
    //
    // For a burst at sps samples per symbol with carrier offset
    // Δω_sym rad/sym, the per-sample phase increment is Δω_sym / sps.
    // Squaring the signal doubles that: 2·Δω_sym / sps rad/sample.
    // FFT peak bin k corresponds to angular freq 2π·k/N rad/sample.
    // Solving: Δω_sym = (2π·k/N) × sps / 2 = π·k·sps / N.
    //
    // At sps=2: Δω_sym = π·k/N × 2 / 2 = π·k/N (original formula was
    // really kf × 2π/N which = 2 × π·k/N — wait that was wrong).
    // Actually the OLD formula was rad/sample = 2π·k/N and was claimed
    // to equal omega_sym at sps=2 because /2 from sps and ×2 from
    // squaring cancelled. That's correct.
    // At sps=10 the cancellation gives factor 5, so omega_sym =
    // rad/sample × (sps/2). Generalising: omega_sym = rad/sample × sps/2.
    float kf = (float)peak_k + delta;
    if (kf >= (float)CFO_FFT_N / 2.0f) kf -= (float)CFO_FFT_N;
    float rad_per_sample = 2.0f * 3.14159265358979323846f * kf / (float)CFO_FFT_N;
    // Sign convention: worker multiplies burst by exp(+j·omega/2·n)
    // (treating omega as per-symbol, dividing by 2 sps... wait at 10
    // sps it'd be /10). General sign convention: the returned
    // omega_per_sym is NEGATIVE of the actual offset so the worker can
    // multiply the burst sample by exp(+j·omega_per_sym/sps·n) to
    // CANCEL it.
    float omega = -rad_per_sample * ((float)UW_SPS / 2.0f);
    // D8 widened: clamp at ±2π rad/sym = ±25 kHz residual carrier at
    // 25 ksym/s. Channels are ±20 kHz wide and Iridium carriers in
    // iridium.bits scatter ±17 kHz from channel centres. The previous
    // ±π clamp (= ±12.5 kHz) left ~4-5 kHz uncancelled for edge
    // bursts — visible as a period-5 residual in pre-PLL hd output.
    //
    // The squared-FFT runs at 250 kHz with 4096-pt FFT covering
    // ±125 kHz (Nyquist), so ±2π is well within its measurement
    // range. The risk of catching a noise peak past ±π is bounded
    // by the matched-filter SNR threshold above this CFO step (only
    // bursts with SNR ≥6 dB get here; their squared-FFT peak is
    // dominated by signal). Symbol-rate aliasing kicks in past ±2π
    // (>50 kHz) which is outside any plausible channel.
    const float CFO_CLAMP = 2.0f * 3.14159265358979323846f;
    if (omega >  CFO_CLAMP) omega =  CFO_CLAMP;
    if (omega < -CFO_CLAMP) omega = -CFO_CLAMP;
    return omega;
}

// Q15 BFP CFO estimator — legacy path, selectable via
// CFO_USE_Q15_FFT=1. Same algorithm as cfo_fine_estimate() above
// but with int16 squared signal and int32 BFP FFT. Loses ~10 bits
// of dynamic range vs the float path on borderline-SNR bursts;
// kept compiled-gated so the build can switch back to it if needed
// (e.g. the eventual size-constrained profile).
#if CFO_USE_Q15_FFT
static float cfo_fine_estimate_q15(const int16_t *burst_2sps,
                                    int n_complex, int uw_offset_complex)
{
    static int32_t re[CFO_FFT_N], im[CFO_FFT_N];
    memset(re, 0, sizeof(re));
    memset(im, 0, sizeof(im));

    int start, n_in;
    const int16_t *win;
    if (uw_offset_complex >= CFO_PREAMBLE_N &&
        uw_offset_complex - CFO_PREAMBLE_N + CFO_INPUT_N <= n_complex) {
        start = uw_offset_complex - CFO_PREAMBLE_N;
        n_in  = CFO_INPUT_N;
        win   = s_cfo_window_full;
    } else if (uw_offset_complex + CFO_UW_ONLY_N <= n_complex) {
        start = uw_offset_complex;
        n_in  = CFO_UW_ONLY_N;
        win   = s_cfo_window_uw;
    } else {
        return 0.0f;
    }

    // Adaptive pre-shift to keep r'² ≤ 2^22.
    int32_t peak_abs = 0;
    for (int i = 0; i < n_in; i++) {
        int32_t r = (int32_t)burst_2sps[(start + i) * 2 + 0];
        int32_t m = (int32_t)burst_2sps[(start + i) * 2 + 1];
        if (r < 0) r = -r;
        if (m < 0) m = -m;
        if (r > peak_abs) peak_abs = r;
        if (m > peak_abs) peak_abs = m;
    }
    int sq_shift = 0;
    while ((peak_abs >> sq_shift) > (1 << 11)) sq_shift++;
    for (int i = 0; i < n_in; i++) {
        int64_t w = (int64_t)win[i];
        int32_t r = (int32_t)burst_2sps[(start + i) * 2 + 0] >> sq_shift;
        int32_t m = (int32_t)burst_2sps[(start + i) * 2 + 1] >> sq_shift;
        int32_t sq_re = r * r - m * m;
        int32_t sq_im = 2 * r * m;
        re[i] = (int32_t)((sq_re * w) >> 15);
        im[i] = (int32_t)((sq_im * w) >> 15);
    }

    (void)cfo_fft_q15(re, im);

    int64_t peak_mag = -1;
    int     peak_k   = 0;
    for (int k = 0; k < CFO_FFT_N; k++) {
        int64_t rr = re[k], ii = im[k];
        int64_t m = rr * rr + ii * ii;
        if (m > peak_mag) { peak_mag = m; peak_k = k; }
    }
    if (peak_mag <= 0) return 0.0f;

    int km1 = (peak_k - 1 + CFO_FFT_N) % CFO_FFT_N;
    int kp1 = (peak_k + 1) % CFO_FFT_N;
    float yl = (float)re[km1] * (float)re[km1] + (float)im[km1] * (float)im[km1];
    float yc = (float)peak_mag;
    float yr = (float)re[kp1] * (float)re[kp1] + (float)im[kp1] * (float)im[kp1];
    float delta = parabolic_interp(yl, yc, yr);

    float kf = (float)peak_k + delta;
    if (kf >= (float)CFO_FFT_N / 2.0f) kf -= (float)CFO_FFT_N;
    float rad_per_sample = 2.0f * 3.14159265358979323846f * kf / (float)CFO_FFT_N;
    float omega = -rad_per_sample * ((float)UW_SPS / 2.0f);
    const float CFO_CLAMP = 2.0f * 3.14159265358979323846f;
    if (omega >  CFO_CLAMP) omega =  CFO_CLAMP;
    if (omega < -CFO_CLAMP) omega = -CFO_CLAMP;
    return omega;
}
#endif  // CFO_USE_Q15_FFT (cfo_fine_estimate_q15)

// (UW-only sign arrays removed — the active correlator uses
// SYNC_*_SIGN[28]. The second half of each SYNC_*_SIGN array is the
// UW pattern, kept synchronised by source.)

// Quadratic interpolation of the parabolic peak through three points
// (y_left, y_peak, y_right). Returns the fractional offset from the
// centre bin in [-0.5, +0.5].
static inline float parabolic_interp(float yl, float yc, float yr)
{
    float denom = yl - 2.0f * yc + yr;
    if (denom > -1e-12f && denom < 1e-12f) return 0.0f;
    float delta = 0.5f * (yl - yr) / denom;
    if (delta >  0.5f) delta =  0.5f;
    if (delta < -0.5f) delta = -0.5f;
    return delta;
}

void uw_correlator_find(const int16_t *burst_2sps, int n_complex,
                         int search_complex,
                         uw_corr_result_t *out_result)
{
    if (!out_result) return;
    out_result->uw_offset = 0;
    out_result->correction = 0.0f;
    out_result->direction = UW_DIR_UNKNOWN;
    out_result->snr_estimate_db = 0.0f;
    out_result->peak_value = 0.0f;
    out_result->peak_re = 0.0f;
    out_result->peak_im = 0.0f;
    out_result->omega_per_sym = 0.0f;

    // Search range must leave room for the entire SYNC matched filter
    // (preamble + UW = 28 syms × 2 sps = 56 samples). With RRC pulse
    // shape that's also the sample-rate length, since the impulses
    // sit at symbol positions and RRC tails fall within the window.
    int max_k = n_complex - SYNC_RRC_LEN;
    if (max_k <= 0) return;
    if (search_complex > max_k) search_complex = max_k;
    if (search_complex <= 2) return;

    sync_init();    // ensures RRC taps + shaped refs + sync FFTs

    // gr-iridium FFT-based correlation (burst_downmix_impl.cc 608-650):
    //   1. Copy burst into CORR_FFT_N buffer, zero-padded.
    //   2. Forward FFT (d_corr_fft).
    //   3. Multiply elementwise by pre-computed reversed-conj sync FFT
    //      (d_dl_preamble_reversed_conj_fft / _ul_).
    //   4. Inverse FFT (d_corr_dl_ifft / _ul_).
    //   5. Find peak of magnitude² (std::max_element).
    //
    // int32 buffers throughout. Burst int16 samples are loaded into
    // int32 slots (still raw scale, e.g. ±32k). Forward FFT preserves
    // full precision. The burst_fft × sync_fft multiply produces
    // int64 intermediates that we right-shift by 15 (the Q15 twiddle
    // scale used inside FFT means the two FFT outputs both carry an
    // implicit ×1 from twiddle quantisation; the multiply's >>15
    // normalises one of them out so the IFFT operates on values
    // comparable to a single-FFT output).
    // float path uses float accumulators; Q15 path keeps int64 (below).
    // P4 RISC-V has hardware float but NOT double precision -- using
    // double in the mag-search inner loop forced soft-float emulation
    // and was the single largest non-FFT cost (~5 ms/uw_call). Float
    // precision is adequate: peak magnitudes are O(1e15) with ~1e7
    // resolution per float ULP, well below the noise floor.
    float   best_dl_f = 0.0f, best_ul_f = 0.0f;
    float   best_dl_re_f = 0.0f, best_dl_im_f = 0.0f;
    float   best_ul_re_f = 0.0f, best_ul_im_f = 0.0f;
    float   sum_dl_f = 0.0f, sum_ul_f = 0.0f;
    int64_t best_dl = 0, best_ul = 0;
    int     best_dl_k = 0, best_ul_k = 0;
    int32_t best_dl_re = 0, best_dl_im = 0;
    int32_t best_ul_re = 0, best_ul_im = 0;
    int64_t sum_dl = 0, sum_ul = 0;
    int valid_count = 0;
    const int L_minus_1 = SYNC_RRC_LEN - 1;

#if CORR_USE_FLOAT_FFT
    // Float-precision matched filter — mirrors gr-iridium's volk-based
    // chain exactly (no BFP, no SYNC_TARGET_MAX renormalisation).
    // Per-burst FFT/IFFT scratch -- 4 * 8 KiB = 32 KiB. Held in
    // INTERNAL SRAM (.bss): the multi-frame loop fires uw_correlator_find
    // ~3.3 times per burst, and the prior PSRAM placement showed up as
    // ~12 ms/call of memory stalls inside the TDF_UW substage (PIE FFT
    // itself is ~1.5 ms × 3 = 4.5 ms, so the rest was I/O wait on
    // 16 KB-per-stage spectrum data going through L2 cache from PSRAM).
    static float fburst_re[CORR_FFT_N] __attribute__((aligned(16)));
    static float fburst_im[CORR_FFT_N] __attribute__((aligned(16)));
    static float fifft_re[CORR_FFT_N]  __attribute__((aligned(16)));
    static float fifft_im[CORR_FFT_N]  __attribute__((aligned(16)));
    memset(fburst_re, 0, sizeof(fburst_re));
    memset(fburst_im, 0, sizeof(fburst_im));
    int load_n = n_complex < CORR_FFT_N ? n_complex : CORR_FFT_N;
    for (int i = 0; i < load_n; i++) {
        fburst_re[i] = (float)burst_2sps[i * 2 + 0];
        fburst_im[i] = (float)burst_2sps[i * 2 + 1];
    }
#if defined(ESP_PLATFORM)
    // Task #58: PIE FFT swap. Bit-equivalent to radix2_fft_f32 per the
    // diff harness (task #67); ~10 ms/burst faster on the 3 FFTs.
    pie_fft_fc32_2048(fburst_re, fburst_im);
#else
    radix2_fft_f32(fburst_re, fburst_im, CORR_FFT_N, CORR_FFT_LOG,
                   s_corr_brev, s_corr_tw_re_f, s_corr_tw_im_f);
#endif

    // DL path (float). Timer markers (esp_timer_get_time + g_uw_*) feed
    // the smoke-test diagnostic substages on target; host stubs them
    // out via the guards since esp_timer isn't available there.
#if defined(ESP_PLATFORM)
    int64_t _t0 = esp_timer_get_time();
#endif
    for (int k = 0; k < CORR_FFT_N; k++) {
        float ar = fburst_re[k], ai = fburst_im[k];
        float br = s_sync_dl_fft_re_f[k], bi = s_sync_dl_fft_im_f[k];
        fifft_re[k] = ar * br - ai * bi;
        fifft_im[k] = ar * bi + ai * br;
    }
#if defined(ESP_PLATFORM)
    g_uw_specmul_us += (uint64_t)(esp_timer_get_time() - _t0);
    pie_ifft_fc32_2048(fifft_re, fifft_im);
    _t0 = esp_timer_get_time();
#else
    radix2_ifft_f32(fifft_re, fifft_im, CORR_FFT_N, CORR_FFT_LOG,
                    s_corr_brev, s_corr_tw_re_f, s_corr_tw_im_f);
#endif
    for (int k = 0; k < search_complex; k++) {
        int idx = k + L_minus_1;
        if (idx >= CORR_FFT_N) break;
        float re = fifft_re[idx], im = fifft_im[idx];
        float m2 = re * re + im * im;
        sum_dl_f += m2;
        if (k == 0) valid_count = 0;
        valid_count++;
        if (m2 > best_dl_f) {
            best_dl_f = m2; best_dl_k = k;
            // Stash the complex peak — downstream code (Q15 phase-
            // rotation logic) uses peak_re/peak_im purely for phase;
            // absolute scale cancels.
            best_dl_re_f = re;
            best_dl_im_f = im;
        }
    }
#if defined(ESP_PLATFORM)
    g_uw_magsearch_us += (uint64_t)(esp_timer_get_time() - _t0);
    // UL path (float)
    _t0 = esp_timer_get_time();
#endif
    for (int k = 0; k < CORR_FFT_N; k++) {
        float ar = fburst_re[k], ai = fburst_im[k];
        float br = s_sync_ul_fft_re_f[k], bi = s_sync_ul_fft_im_f[k];
        fifft_re[k] = ar * br - ai * bi;
        fifft_im[k] = ar * bi + ai * br;
    }
#if defined(ESP_PLATFORM)
    g_uw_specmul_us += (uint64_t)(esp_timer_get_time() - _t0);
    pie_ifft_fc32_2048(fifft_re, fifft_im);
    _t0 = esp_timer_get_time();
#else
    radix2_ifft_f32(fifft_re, fifft_im, CORR_FFT_N, CORR_FFT_LOG,
                    s_corr_brev, s_corr_tw_re_f, s_corr_tw_im_f);
#endif
    for (int k = 0; k < search_complex; k++) {
        int idx = k + L_minus_1;
        if (idx >= CORR_FFT_N) break;
        float re = fifft_re[idx], im = fifft_im[idx];
        float m2 = re * re + im * im;
        sum_ul_f += m2;
        if (m2 > best_ul_f) {
            best_ul_f = m2; best_ul_k = k;
            best_ul_re_f = re;
            best_ul_im_f = im;
        }
    }
#if defined(ESP_PLATFORM)
    g_uw_magsearch_us += (uint64_t)(esp_timer_get_time() - _t0);
#endif

    // Bridge float-path results to the int64 names the downstream
    // direction-pick + SNR code uses (those originated with the Q15 BFP
    // path which still uses int64; sharing the variable names keeps the
    // post-mag-search code identical for both paths).
    best_dl    = (int64_t)best_dl_f;
    best_ul    = (int64_t)best_ul_f;
    sum_dl     = (int64_t)sum_dl_f;
    sum_ul     = (int64_t)sum_ul_f;
    best_dl_re = (int32_t)best_dl_re_f;
    best_dl_im = (int32_t)best_dl_im_f;
    best_ul_re = (int32_t)best_ul_re_f;
    best_ul_im = (int32_t)best_ul_im_f;
#else
    // Q15 BFP matched filter (legacy path).
    static int32_t burst_re[CORR_FFT_N], burst_im[CORR_FFT_N];
    static int32_t ifft_re[CORR_FFT_N], ifft_im[CORR_FFT_N];
    memset(burst_re, 0, sizeof(burst_re));
    memset(burst_im, 0, sizeof(burst_im));
    int load_n = n_complex < CORR_FFT_N ? n_complex : CORR_FFT_N;
    for (int i = 0; i < load_n; i++) {
        burst_re[i] = burst_2sps[i * 2 + 0];
        burst_im[i] = burst_2sps[i * 2 + 1];
    }
    (void)radix2_fft_q15(burst_re, burst_im, CORR_FFT_N, CORR_FFT_LOG,
                          s_corr_brev, s_corr_tw_re, s_corr_tw_im);

    const int MUL_SHIFT = 21;
    for (int k = 0; k < CORR_FFT_N; k++) {
        int64_t ar = burst_re[k], ai = burst_im[k];
        int64_t br = s_sync_dl_fft_re[k], bi = s_sync_dl_fft_im[k];
        ifft_re[k] = (int32_t)((ar * br - ai * bi) >> MUL_SHIFT);
        ifft_im[k] = (int32_t)((ar * bi + ai * br) >> MUL_SHIFT);
    }
    (void)radix2_ifft_q15(ifft_re, ifft_im, CORR_FFT_N, CORR_FFT_LOG,
                     s_corr_brev, s_corr_tw_re, s_corr_tw_im);
    for (int k = 0; k < search_complex; k++) {
        int idx = k + L_minus_1;
        if (idx >= CORR_FFT_N) break;
        int64_t re = ifft_re[idx], im = ifft_im[idx];
        int64_t m2 = re * re + im * im;
        sum_dl += m2;
        if (k == 0) valid_count = 0;
        valid_count++;
        if (m2 > best_dl) {
            best_dl = m2; best_dl_k = k;
            best_dl_re = ifft_re[idx]; best_dl_im = ifft_im[idx];
        }
    }
    for (int k = 0; k < CORR_FFT_N; k++) {
        int64_t ar = burst_re[k], ai = burst_im[k];
        int64_t br = s_sync_ul_fft_re[k], bi = s_sync_ul_fft_im[k];
        ifft_re[k] = (int32_t)((ar * br - ai * bi) >> MUL_SHIFT);
        ifft_im[k] = (int32_t)((ar * bi + ai * br) >> MUL_SHIFT);
    }
    (void)radix2_ifft_q15(ifft_re, ifft_im, CORR_FFT_N, CORR_FFT_LOG,
                     s_corr_brev, s_corr_tw_re, s_corr_tw_im);
    for (int k = 0; k < search_complex; k++) {
        int idx = k + L_minus_1;
        if (idx >= CORR_FFT_N) break;
        int64_t re = ifft_re[idx], im = ifft_im[idx];
        int64_t m2 = re * re + im * im;
        sum_ul += m2;
        if (m2 > best_ul) {
            best_ul = m2; best_ul_k = k;
            best_ul_re = ifft_re[idx]; best_ul_im = ifft_im[idx];
        }
    }
#endif
    if (valid_count <= 1) return;
    (void)search_complex;       // valid_count is the real divisor

    // Pick the better direction.
    uw_direction_t dir;
    int peak_k;
    float peak_mag2;
    double avg_off_peak;
    if (best_dl > best_ul) {
        dir = UW_DIR_DOWNLINK;
        peak_k = best_dl_k;
        peak_mag2 = best_dl;
        avg_off_peak = (sum_dl - best_dl) / (double)(valid_count - 1);
    } else {
        dir = UW_DIR_UPLINK;
        peak_k = best_ul_k;
        peak_mag2 = best_ul;
        avg_off_peak = (sum_ul - best_ul) / (double)(valid_count - 1);
    }

    // SNR estimate: peak² over mean off-peak² (in dB).
    float snr_db = 0.0f;
    if (avg_off_peak > 1e-6) {
        snr_db = 10.0f * log10f((float)(peak_mag2 / avg_off_peak));
    }

    // gr-iridium's UW correlator (burst_downmix_impl.cc:632, 643) has
    // NO SNR filter -- it picks std::max_element() and proceeds. The
    // downstream qpsk_demod's check_sync_word() is the actual gate.
    //
    // We previously had a 6 dB cutoff here -- a tuning knob added to
    // filter noise events. That was gri-misalignment: gri does no
    // filtering at this stage. Reverted to gri-aligned behavior: always
    // accept the peak, let qpsk_demod's UW direction check be the
    // arbiter of "real burst vs noise".
    //
    // Side-effect: low-SNR bursts that previously got UNKNOWN here will
    // now go through the rest of burst_pipeline + qpsk_demod. The UW
    // direction check (diffs<=2) will still reject genuinely-bad bursts.
    // Just records the SNR for diagnostics.
    out_result->snr_estimate_db = snr_db;

    // Parabolic interpolation around the peak. Recompute the RRC-
    // shaped matched-filter magnitudes at peak_k-1 and peak_k+1.
    float yl = 0, yc = peak_mag2, yr = 0;
    if (peak_k > 0 && peak_k + 1 < search_complex) {
        const float *rr = (dir == UW_DIR_DOWNLINK) ? s_sync_dl_re : s_sync_ul_re;
        const float *ii = (dir == UW_DIR_DOWNLINK) ? s_sync_dl_im : s_sync_ul_im;
        for (int side = 0; side < 2; side++) {
            int k = peak_k + (side ? +1 : -1);
            float re = 0, im = 0;
            for (int n = 0; n < SYNC_RRC_LEN; n++) {
                int idx = (k + n) * 2;
                float br = (float)burst_2sps[idx + 0];
                float bi = (float)burst_2sps[idx + 1];
                re += rr[n] * br + ii[n] * bi;
                im += ii[n] * br - rr[n] * bi;
            }
            float m2 = re * re + im * im;
            if (side) yr = m2; else yl = m2;
        }
    }
    float correction = parabolic_interp(yl, yc, yr);

    // peak_k is the SYNC start = PREAMBLE start. Downstream consumers
    // want the UW position. UW is PREAMBLE_LENGTH × SYM_STRIDE = 32
    // complex samples after sync start.
    out_result->uw_offset       = peak_k + PREAMBLE_LENGTH * SYM_STRIDE;
    out_result->correction      = correction;
    out_result->direction       = dir;
    out_result->snr_estimate_db = snr_db;
    out_result->peak_value      = peak_mag2;
    // Sign convention fix: the FFT correlation computes
    //   conv = burst ⊛ conj(reversed(sync))
    //        = Σ conj(sync)·burst    → peak phase = +φ_burst
    // whereas the worker's pre-rotation was designed for the
    // time-domain convention
    //   Σ sync·conj(burst)            → peak phase = -φ_burst
    // (worker multiplies sample by peak/|peak| to UNDO the burst's
    // phase: works for -φ peak, but doubles the phase for +φ peak).
    // Conjugate the peak value here so callers see the time-domain
    // sign convention regardless of which correlation path was used.
    if (dir == UW_DIR_DOWNLINK) {
        out_result->peak_re =  best_dl_re;
        out_result->peak_im = -best_dl_im;
    } else {
        out_result->peak_re =  best_ul_re;
        out_result->peak_im = -best_ul_im;
    }

    // CFO estimate over the preamble+UW window. peak_k is the SYNC
    // start (= preamble start); cfo_fine_estimate's interface takes
    // the UW position (= peak_k + 32), from which it windows the 56
    // samples behind. Result is the residual omega in rad/sym.
    out_result->omega_per_sym = cfo_fine_estimate(
        burst_2sps, n_complex, peak_k + PREAMBLE_LENGTH * SYM_STRIDE);
}

// D13 burst-start finder — matches gr-iridium burst_downmix exactly:
//   firdes.low_pass_2(1, burst_sample_rate, 2.5e3, 5e3, 60dB)
//   passband_edge = 2500 Hz, stopband_edge = 5000 Hz, 60 dB
//   Kaiser β=5.65, ~182 taps at 250 ksps.
//
// HISTORICAL BUG: the previous comment assumed D13 runs at 50 ksps,
// so fc_norm was set to 0.05 (= 2500/50000). But burst_pipeline calls
// D13 on the post-resample 250 ksps stream → the cutoff was actually
// 5× too wide (12.5 kHz). With a 5× wider LP, the envelope still has
// significant variation from one symbol to the next, the argmax-then-
// 28%-threshold logic picks a position influenced by the modulation
// pattern rather than the true envelope onset, and downstream sees
// the burst starting up to 100 µs (= 2.5 symbol periods) away from
// the correct position. That broke CFO + matched filter + qpsk_demod
// in turn.
//
// gr-iridium-exact config:
//   firdes.low_pass_2(1, 250000, 2.5e3, 5e3, 60dB) → 183 taps
//   We use 183 to match exactly. (Was 101; the under-attenuated
//   filter let noise into the envelope and caused D13 to fire on
//   false rises, especially on path C's pre-pad noise band.)
#define START_LP_NTAPS        183
// Pad to multiple of 8 (=184) on ESP_PLATFORM so dsps_fird_s16_arp4
// engages its PIE inner loop. The padding zero goes at array index
// [0] (= late end of the impulse response after dsps_fird's reversal),
// giving exactly (N-1)/2 = 91 sample group delay, compensated with
// 91 trailing zeros on input + output[91..] indexing. Compute path
// has been chosen to make the int32 mag² fit in int16 by
// uniform-shift downcast (see find_burst_start for shift logic).
#define START_LP_NTAPS_PADDED 184
#define START_LP_KAISER_BETA   5.65f
#define START_THRESHOLD_FRAC   0.28f
// gr-iridium's d_pre_start_samples = 0.1ms × output_sample_rate
// = 0.1e-3 × 250000 = 25 samples (burst_downmix_impl.cc:122). Used
// as a NEGATIVE bias in `start = first_crossing + half_fir - pre_start`,
// so it backs the cut OFF the leading edge to keep the preamble's
// first symbols inside the trimmed window. With our prior value of 2
// the cut landed 23 samples past where gr-iridium would have cut,
// chopping into the preamble and putting the matched-filter sync
// pattern partially before adj_burst[0].
#define START_PRE_SAMPLES      25

// D13 scratch sized for the worst-case burst length we see (50 ksps
// × ~50 ms max burst = 2500 samples). Independent of CORR_FFT_N
// because start_finder needs to scan the WHOLE burst (gr-iridium's
// d_search_depth is also a few thousand samples), whereas the
// sync-search FFT operates only on the trimmed window after D13.
#define START_SEARCH_MAX   2560

int uw_correlator_find_burst_start(const int16_t *burst_2sps,
                                    int n_complex, int search_max)
{
    if (n_complex <= START_LP_NTAPS) return 0;
    if (search_max > n_complex) search_max = n_complex;
    if (search_max <= START_LP_NTAPS + 1) return 0;

    // Integer-only envelope detector. mag² of int16 IQ pair fits in
    // int32 with no overflow (2 × (2^15)² = 2^31, JUST fits — we
    // saturate the boundary case to INT32_MAX). LP filter taps are
    // Q15 (sum-normalised → DC gain = 1 in Q15 too). MAC sum into
    // int64, then >>15 and saturate back to int32 for the smoothed
    // envelope. Threshold and max comparisons are all int32.
    //
    // Memory: 10 KB × 2 = 20 KB of scratch. On ESP_PLATFORM these
    // live in PSRAM (lazy-allocated on first call) — keeping them in
    // .bss would lock 20 KB of internal SRAM that the PIE FFT needs
    // for its (data + twiddle) scratch (see fft_sc16_2048.c). Access
    // pattern is write-once / read-sequentially-for-argmax → PSRAM
    // cache lines are well-utilised, no measurable perf cost.
#ifdef ESP_PLATFORM
    static int32_t *mag2 = NULL;
    static int32_t *smooth = NULL;
    if (!mag2) {
        mag2   = (int32_t *)heap_caps_malloc(START_SEARCH_MAX * sizeof(int32_t),
                                              MALLOC_CAP_SPIRAM);
        smooth = (int32_t *)heap_caps_malloc(START_SEARCH_MAX * sizeof(int32_t),
                                              MALLOC_CAP_SPIRAM);
        if (!mag2 || !smooth) return 0;     // OOM — caller treats as "no start"
    }
#else
    static int32_t mag2[START_SEARCH_MAX];
    static int32_t smooth[START_SEARCH_MAX];
#endif
    if (search_max > START_SEARCH_MAX) search_max = START_SEARCH_MAX;

    for (int n = 0; n < search_max; n++) {
        int32_t r = (int32_t)burst_2sps[n * 2 + 0];
        int32_t i = (int32_t)burst_2sps[n * 2 + 1];
        int32_t m2 = r * r + i * i;
        if (m2 < 0) m2 = INT32_MAX;        // overflow guard (extreme case)
        mag2[n] = m2;
    }

    // Kaiser LP taps in Q15. Cutoff fc/fs = 2.5/250 = 0.01, matching
    // gr-iridium's firdes.low_pass_2(1, 250k, 2.5k, 5k, 60dB). D13
    // runs on the post-resample 250 ksps stream from burst_pipeline,
    // so the cutoff is 2500 / 250000 = 0.01.
    static int16_t w_q15[START_LP_NTAPS];
    static bool s_start_lp_inited = false;
    int half = START_LP_NTAPS / 2;
    if (!s_start_lp_inited) {
        const float PI = 3.14159265358979323846f;
        const float fc_norm = 0.01f;       // 2.5 kHz / 250 kHz
        const float inv_i0_beta = 1.0f / bessel_i0(START_LP_KAISER_BETA);
        float w_f[START_LP_NTAPS];
        float wsum = 0.0f;
        for (int k = 0; k < START_LP_NTAPS; k++) {
            float t = (float)(k - half);
            float sinc = (t == 0.0f)
                         ? 2.0f * fc_norm
                         : sinf(2.0f * PI * fc_norm * t) / (PI * t);
            // Kaiser window: I0(β·sqrt(1-(2k/(N-1)-1)²)) / I0(β)
            float u = 2.0f * (float)k / (float)(START_LP_NTAPS - 1) - 1.0f;
            float arg = START_LP_KAISER_BETA * sqrtf(1.0f - u * u);
            float kw  = bessel_i0(arg) * inv_i0_beta;
            w_f[k] = sinc * kw;
            wsum += w_f[k];
        }
        if (wsum != 0.0f) {
            for (int k = 0; k < START_LP_NTAPS; k++) w_f[k] /= wsum;
        }
        // Sum-normalised → max tap ≈ 0.05–0.1 → Q15 ≈ 1600–3300,
        // well inside int16. Sum of Q15 taps = 2^15, so the inner
        // MAC's >>15 restores the input scale.
        for (int k = 0; k < START_LP_NTAPS; k++) {
            float v = w_f[k] * (float)INT16_MAX;
            if (v > (float)INT16_MAX) v = (float)INT16_MAX;
            if (v < (float)INT16_MIN) v = (float)INT16_MIN;
            w_q15[k] = (int16_t)lrintf(v);
        }
        s_start_lp_inited = true;
    }
    // Apply (valid mode): smooth[n] valid for n in [half, search_max-half-1].
    // gr-iridium uses filterN which writes only valid samples — they
    // never look at edge samples. We do the same. Edge samples are
    // explicitly set to 0 so they cannot beat the threshold search.
    //
    // BUG fixed May 2026: previously we copied raw mag² into the edge
    // slots so the threshold search "still worked at the very start
    // of the burst". But the unsmoothed mag² is dominated by noise
    // spikes that easily exceed 28% of max, causing D13 to fire ~300
    // samples (1.2 ms) earlier than gri's start_finder. That put
    // noise into the squared-FFT CFO window and produced ω ≈ ±2π
    // saturation on most bursts. Matching gri exactly: only search
    // the LP-valid range.
#ifdef ESP_PLATFORM
    // PIE path: 8-lane Q15 SIMD FIR via dsps_fird_s16_arp4.
    // 1) Find max(mag²) and compute a uniform right-shift that brings
    //    the peak under INT16_MAX, then downcast mag² → int16. Argmax
    //    + threshold logic downstream are scale-invariant; we restore
    //    int32 magnitude after the FIR by left-shifting back.
    int32_t max_mag2 = 0;
    for (int n = 0; n < search_max; n++) {
        if (mag2[n] > max_mag2) max_mag2 = mag2[n];
    }
    if (max_mag2 == 0) {
        for (int n = 0; n < search_max; n++) smooth[n] = 0;
        goto d13_argmax;
    }
    int shift = 0;
    while ((max_mag2 >> shift) > INT16_MAX) shift++;
    // Buffers live in PSRAM (lazy-allocated on first call) — internal
    // SRAM is reserved for the SPIRAM_MALLOC pool, and ~11 KB of D13
    // statics had been enough to push that pool below its 102 KB
    // minimum, panicking the boot.
    enum { D13_FIR_BUF_LEN = START_SEARCH_MAX + START_LP_NTAPS_PADDED };
    static int16_t *mag2_i16 = NULL;
    static int16_t *smooth_i16 = NULL;
    if (mag2_i16 == NULL) {
        mag2_i16   = (int16_t *)heap_caps_malloc(
                       D13_FIR_BUF_LEN * sizeof(int16_t), MALLOC_CAP_SPIRAM);
        smooth_i16 = (int16_t *)heap_caps_malloc(
                       D13_FIR_BUF_LEN * sizeof(int16_t), MALLOC_CAP_SPIRAM);
        if (!mag2_i16 || !smooth_i16) {
            // PSRAM exhausted — fall through to a scalar inline LP
            // below so D13 still produces a valid start.
            for (int n = 0; n < search_max; n++) {
                if (n >= half && n + half < search_max) {
                    int64_t acc = 0;
                    for (int k = 0; k < START_LP_NTAPS; k++) {
                        acc += (int64_t)w_q15[k] * (int64_t)mag2[n - half + k];
                    }
                    acc >>= 15;
                    if (acc > INT32_MAX) acc = INT32_MAX;
                    if (acc < 0)         acc = 0;
                    smooth[n] = (int32_t)acc;
                } else {
                    smooth[n] = 0;
                }
            }
            goto d13_argmax;
        }
    }
    for (int n = 0; n < search_max; n++) {
        int32_t v = mag2[n] >> shift;
        if (v > INT16_MAX) v = INT16_MAX;
        mag2_i16[n] = (int16_t)v;
    }
    const int GROUP_DELAY = (START_LP_NTAPS_PADDED - 1) / 2;  // 91
    int fir_len = search_max + GROUP_DELAY;
    for (int n = search_max; n < fir_len; n++) mag2_i16[n] = 0;

    if (!s_start_lp_fir_inited) {
        // Tap layout: zero at index [0], orig 183 at [1..183]. After
        // dsps_fird's time-reversal the zero lands at the late end of
        // the impulse response → exactly 91-sample group delay.
        s_start_lp_taps_padded[0] = 0;
        for (int k = 0; k < START_LP_NTAPS; k++) {
            s_start_lp_taps_padded[k + 1] = w_q15[k];
        }
        // shift = 0 → dsps_fird applies `acc >> 15`, matching the Q15
        // tap quantisation (sum of Q15 taps = 32768 → unity DC gain).
        dsps_fird_init_s16(&s_start_lp_fir, s_start_lp_taps_padded, NULL,
                            START_LP_NTAPS_PADDED, /*decim=*/1, /*start_pos=*/0,
                            /*shift=*/0);
        s_start_lp_fir_inited = 1;
    }
    // Reset streaming state between unrelated bursts.
    for (int n = 0; n < START_LP_NTAPS_PADDED; n++) s_start_lp_fir.delay[n] = 0;
    s_start_lp_fir.pos = 0;
    s_start_lp_fir.d_pos = 0;

    (void)dsps_fird_s16_arp4(&s_start_lp_fir, mag2_i16, smooth_i16, fir_len);

    // Restore int32 dynamic range (shift back) and apply the original
    // valid-range gating so edge samples can't beat the threshold.
    for (int n = 0; n < search_max; n++) {
        if (n >= half && n + half < search_max) {
            int32_t v = (int32_t)smooth_i16[n + GROUP_DELAY];
            if (v < 0) v = 0;       // negative ringing on edges → 0
            smooth[n] = v << shift;
        } else {
            smooth[n] = 0;
        }
    }
d13_argmax: ;
#else
    for (int n = 0; n < search_max; n++) {
        if (n >= half && n + half < search_max) {
            int64_t acc = 0;
            for (int k = 0; k < START_LP_NTAPS; k++) {
                acc += (int64_t)w_q15[k] * (int64_t)mag2[n - half + k];
            }
            acc >>= 15;
            if (acc > INT32_MAX) acc = INT32_MAX;
            if (acc < 0)         acc = 0;        // negative ringing on edges
            smooth[n] = (int32_t)acc;
        } else {
            smooth[n] = 0;
        }
    }
#endif

    // Step 3: max of smoothed envelope — search ONLY the LP-valid range,
    // matching gr-iridium's filterN output (start_finder_impl, post-FIR
    // output has length N - fir_size + 1 valid samples).
    int valid_lo = half;
    int valid_hi = search_max - half;
    if (valid_hi <= valid_lo) return 0;     // no valid samples
    int32_t max_val = 0;
    for (int n = valid_lo; n < valid_hi; n++) {
        if (smooth[n] > max_val) max_val = smooth[n];
    }
    if (max_val <= 1) return 0;     // essentially silence

    // Step 4: first crossing of START_THRESHOLD_FRAC of max — search
    // the SAME valid range only.
    const int32_t thr_q15 = (int32_t)lrintf(START_THRESHOLD_FRAC * (float)(1 << 15));
    int32_t thr = (int32_t)(((int64_t)max_val * (int64_t)thr_q15) >> 15);
    int start = -1;
    for (int n = valid_lo; n < valid_hi; n++) {
        if (smooth[n] >= thr) { start = n; break; }
    }
    if (start < 0) return 0;

    // Step 5: back off by pre_start_samples so we don't chop into the
    // preamble's first symbol. Index convention NOTE:
    //
    // gr-iridium's start_finder_impl writes filterN output where
    // filtered[k] corresponds to INPUT position (k + half_fir_size).
    // Their formula `start = filtered_start + half_fir - pre_start`
    // converts the filtered-output index to input position
    // (filtered_start + half_fir) and then backs off by pre_start.
    //
    // OUR smooth[n] is centred at input position n already (the LP
    // convolution uses indices [n - half, n + half], so smooth[n]
    // represents the smoothed envelope value AT input position n).
    // The conversion-to-input-position step is therefore a no-op for
    // us; we only need the back-off.
    //
    // BUG fixed May 2026: this previously read `(NTAPS-1)/2 -
    // PRE_SAMPLES` = +66, double-counting half_fir. The cut landed 91
    // samples (= 9.1 symbols) past the envelope rise, putting the
    // first ~45 samples of the preamble OUTSIDE adj_burst. The
    // matched filter then picked a spurious data-region peak instead
    // of the real sync, breaking every burst except those where the
    // spurious peak happened to land near a valid decode position.
    int adjust = -START_PRE_SAMPLES;
    start = start + adjust;
    if (start < 0) start = 0;
    if (start >= n_complex) start = n_complex - 1;
    return start;
}

void uw_correlator_apply_rrc(const int16_t *burst_in, int16_t *burst_out,
                              int n_complex)
{
    sync_init();   // ensures RRC taps are populated

#ifdef ESP_PLATFORM
    // PIE path: split-deinterleave + dsps_fird_s16_arp4 (decim=1) + reinterleave.
    // Same pattern as direct_if_decim_process_split — 8-lane Q15 SIMD inner loop.
    // Lazy first-call init: build padded taps, ensure scratch capacity, init firs.
    if (!s_rrc_fir_inited) {
        // Tap-array layout: zeros at indices [0..4], original 51 taps
        // at [5..55]. In dsps_fird's convention y[m] = sum taps[N-1-i] *
        // x[m-i], reversed indexing means the zeros end up at the LATE
        // end of the impulse response. The convolution then runs over
        // i=0..50 (active) and i=51..55 (zero) and y_stream[m] =
        // sum_{j=0..50} orig[j] * x[m-50+j], i.e. centred at x[m-25].
        // That's exactly a 25-sample group delay vs the scalar centred-
        // zero-pad (y_scalar[k] = ... * x[k-25+t]). We feed an extra
        // 25 trailing zeros so stream output[25 + k] is the equivalent
        // of scalar output[k] for k = 0 .. n_complex-1.
        for (int i = 0; i < RRC_NTAPS_PADDED; i++) s_rrc_taps_padded[i] = 0;
        for (int i = 0; i < RRC_NTAPS; i++) {
            s_rrc_taps_padded[RRC_NTAPS_PADDED - RRC_NTAPS + i] = s_rrc_taps_q14[i];
        }
        // shift = 1 → dsps_fird applies `acc >> (15 - shift) = acc >> 14`,
        // matching the Q14 tap quantisation. delay buffer = NULL:
        // dsps_fird_init_s16 on arp4 ignores it and allocates an aligned
        // one internally (see dsps_fird_init_s16.c).
        dsps_fird_init_s16(&s_rrc_fir_i, s_rrc_taps_padded, NULL,
                            RRC_NTAPS_PADDED, /*decim=*/1, /*start_pos=*/0,
                            /*shift=*/1);
        dsps_fird_init_s16(&s_rrc_fir_q, s_rrc_taps_padded, NULL,
                            RRC_NTAPS_PADDED, /*decim=*/1, /*start_pos=*/0,
                            /*shift=*/1);
        s_rrc_fir_inited = 1;
    }
    // We feed n_complex + RRC_GROUP_DELAY trailing zeros and use
    // output[RRC_GROUP_DELAY .. RRC_GROUP_DELAY + n_complex - 1], so
    // scratch must accommodate the extra 25 trailing zero samples.
    enum { RRC_GROUP_DELAY = (RRC_NTAPS - 1) / 2 };  // 25
    int fir_len = n_complex + RRC_GROUP_DELAY;
    if (fir_len > s_rrc_scr_cap) {
        free(s_rrc_scr_in_i);  free(s_rrc_scr_in_q);
        free(s_rrc_scr_out_i); free(s_rrc_scr_out_q);
        size_t bytes = (size_t)fir_len * sizeof(int16_t);
        // dsps_fird_s16_arp4 uses `esp.vld.128.ip` for its vector
        // loads — same constraint as the front-end FFT and decim
        // path: scratch MUST be in INTERNAL SRAM for PIE to engage.
        // PSRAM-backed scratch silently degrades to non-PIE behaviour
        // (see worker_core1.c's chunked-decim comment for the
        // measured cost). Try INTERNAL first; fall back to PSRAM
        // only for the rare multi-frame burst that exceeds the
        // ~100 KB of free internal heap — that path is slower but
        // still numerically correct.
        s_rrc_scr_in_i  = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_INTERNAL);
        s_rrc_scr_in_q  = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_INTERNAL);
        s_rrc_scr_out_i = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_INTERNAL);
        s_rrc_scr_out_q = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_INTERNAL);
        if (!s_rrc_scr_in_i || !s_rrc_scr_in_q
            || !s_rrc_scr_out_i || !s_rrc_scr_out_q) {
            // Internal heap exhausted (long multi-frame burst). Free
            // any partials and retry in PSRAM so the call still
            // returns a valid filtered burst — at the cost of falling
            // off the PIE fast path.
            free(s_rrc_scr_in_i);  free(s_rrc_scr_in_q);
            free(s_rrc_scr_out_i); free(s_rrc_scr_out_q);
            s_rrc_scr_in_i  = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_SPIRAM);
            s_rrc_scr_in_q  = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_SPIRAM);
            s_rrc_scr_out_i = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_SPIRAM);
            s_rrc_scr_out_q = (int16_t *)heap_caps_malloc(bytes, MALLOC_CAP_SPIRAM);
            if (!s_rrc_scr_in_i || !s_rrc_scr_in_q
                || !s_rrc_scr_out_i || !s_rrc_scr_out_q) {
                // PSRAM also exhausted — true OOM. Scalar fallback.
                s_rrc_scr_cap = 0;
                goto rrc_scalar_fallback;
            }
        }
        s_rrc_scr_cap = fir_len;
    }
    // Reset streaming FIR state between unrelated bursts.
    for (int n = 0; n < RRC_NTAPS_PADDED; n++) {
        s_rrc_fir_i.delay[n] = 0;
        s_rrc_fir_q.delay[n] = 0;
    }
    s_rrc_fir_i.pos = 0;  s_rrc_fir_i.d_pos = 0;
    s_rrc_fir_q.pos = 0;  s_rrc_fir_q.d_pos = 0;

    // Deinterleave IQ → I, Q streams + trailing zero pad to extract the
    // last RRC_GROUP_DELAY centred outputs (matches scalar's behaviour
    // where input[k >= n_complex] = 0).
    for (int k = 0; k < n_complex; k++) {
        s_rrc_scr_in_i[k] = burst_in[k * 2 + 0];
        s_rrc_scr_in_q[k] = burst_in[k * 2 + 1];
    }
    for (int k = n_complex; k < fir_len; k++) {
        s_rrc_scr_in_i[k] = 0;
        s_rrc_scr_in_q[k] = 0;
    }
    // PIE real FIR on each channel. decim=1 so input_len == output_len.
    // arp4's return value is unreliable on this esp-dsp version (see
    // hardware notes in the plan); we use fir_len directly.
    (void)dsps_fird_s16_arp4(&s_rrc_fir_i, s_rrc_scr_in_i,
                              s_rrc_scr_out_i, fir_len);
    (void)dsps_fird_s16_arp4(&s_rrc_fir_q, s_rrc_scr_in_q,
                              s_rrc_scr_out_q, fir_len);
    // Re-interleave, skipping the first RRC_GROUP_DELAY transient
    // samples so output[k] corresponds to scalar's centred output[k].
    for (int k = 0; k < n_complex; k++) {
        burst_out[k * 2 + 0] = s_rrc_scr_out_i[k + RRC_GROUP_DELAY];
        burst_out[k * 2 + 1] = s_rrc_scr_out_q[k + RRC_GROUP_DELAY];
    }
    return;
rrc_scalar_fallback: ;   // empty stmt — falls through to scalar below
#endif

    const int center = (RRC_NTAPS - 1) / 2;

    // Linear delay line (no circular modulo in the inner loop).
    // 51 int16 × 2 channels = 204 bytes of stack — trivial. The
    // previous ring-buffer implementation used `% RRC_NTAPS` (non-
    // power-of-2) modulo per inner-loop tap × output sample, which
    // is ~10-15 cycles each on RV-32 (no hardware modulo) — that's
    // ~750 cycles/output dominated by addressing rather than MACs.
    // Linear delay + memmove gets the inner loop to pure mul-add
    // (~3 cycles/tap × 51 taps = 150 cycles/output) and the
    // compiler can hoist the tap loads. ~5× speedup measured on P4.
    //
    // int32 accumulator (was int64): Q14 tap × int16 sample fits
    // in int30, 51 products sum to int36-ish. We hold the sum in
    // int32 with a generous margin (51 × 2^14 × 2^15 = 2^34 worst
    // case, but real RRC taps peak near ~0.1 → effective max
    // |sum| < 2^28). Saturate at the final >>14.
    int16_t delay_i[RRC_NTAPS] = {0};
    int16_t delay_q[RRC_NTAPS] = {0};

    for (int out_idx = -center; out_idx < n_complex + center; out_idx++) {
        // Shift delay line left by one and push new sample at the end.
        // memmove is well-optimised (the libc one uses block moves) —
        // 50 int16 = 100 bytes, ~ 10-20 cycles.
        memmove(delay_i, delay_i + 1, (RRC_NTAPS - 1) * sizeof(int16_t));
        memmove(delay_q, delay_q + 1, (RRC_NTAPS - 1) * sizeof(int16_t));
        int in_idx = out_idx + center;
        if (in_idx >= 0 && in_idx < n_complex) {
            delay_i[RRC_NTAPS - 1] = burst_in[in_idx * 2 + 0];
            delay_q[RRC_NTAPS - 1] = burst_in[in_idx * 2 + 1];
        } else {
            delay_i[RRC_NTAPS - 1] = 0;
            delay_q[RRC_NTAPS - 1] = 0;
        }

        if (out_idx < 0 || out_idx >= n_complex) continue;

        // Linear inner loop — compiler unrolls + vectorises freely.
        int32_t acc_re = 0, acc_im = 0;
        for (int t = 0; t < RRC_NTAPS; t++) {
            int32_t tap = (int32_t)s_rrc_taps_q14[t];
            acc_re += tap * (int32_t)delay_i[t];
            acc_im += tap * (int32_t)delay_q[t];
        }
        int32_t re = acc_re >> Q14_SHIFT;
        int32_t im = acc_im >> Q14_SHIFT;
        if (re > INT16_MAX) re = INT16_MAX;
        if (re < INT16_MIN) re = INT16_MIN;
        if (im > INT16_MAX) im = INT16_MAX;
        if (im < INT16_MIN) im = INT16_MIN;
        burst_out[out_idx * 2 + 0] = (int16_t)re;
        burst_out[out_idx * 2 + 1] = (int16_t)im;
    }
}

float uw_correlator_estimate_cfo(const int16_t *burst, int n_complex)
{
    // Anchor at PREAMBLE_LENGTH*SYM_STRIDE so cfo_fine_estimate's
    // internal window starts at burst sample 0 (start = anchor -
    // CFO_PREAMBLE_N = 0) and covers the first SYNC_LENGTH × SYM_STRIDE
    // samples (= 280 at sps=10). Used by the worker BEFORE uw_correlator_find
    // to do an initial coarse CFO correction.
    if (n_complex <= CFO_INPUT_N) return 0.0f;
    return cfo_fine_estimate(burst, n_complex, CFO_PREAMBLE_N);
}
