#!/usr/bin/env python3
"""
Build a host-test fixture from the Albuquerque cf32 capture
(test_data/iridium_downlink_2022-03-17_albuquerque/iridium_cf32.sigmf-data).

Strategy: pick the highest-SNR IDA-DL burst gr-iridium found in the file
(by scanning derivations/iridium.bits), frequency-shift its slice from the
12 MSPS wideband recording to baseband, decimate to 50 ksps (2 sps at the
25 ksym/s symbol rate), and emit:

  - tests/fixtures/fixture_albq_2sps.h     : int16 IQ for qpsk_demod
  - tests/fixtures/fixture_albq_truth.h    : ground truth bits + direction

Usage: tests/scripts/build_albq_fixture.py
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

import numpy as np
from scipy.signal import resample_poly

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SRC_DIR = REPO_ROOT / "test_data" / "iridium_downlink_2022-03-17_albuquerque"
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures"

DATA_PATH = SRC_DIR / "iridium_cf32.sigmf-data"
META_PATH = SRC_DIR / "iridium_cf32.sigmf-meta"
BITS_PATH = SRC_DIR / "derivations" / "iridium.bits"
PARSED_PATH = SRC_DIR / "derivations" / "iridium.parsed"


def load_meta() -> dict:
    meta = json.loads(META_PATH.read_text())
    assert meta["global"]["core:datatype"] == "cf32_le"
    return meta


def parse_bits_file(path: Path) -> list[dict]:
    """
    Each line of iridium.bits looks like:
      RAW: i-<id>-t1 <ms> <freq_hz> N:<snr+offset> I:<idx> <conf>%
           <freqval> <n_symbols> <bit_string>
    We need ms, freq_hz, n_symbols, bits.
    """
    out = []
    for line in path.read_text().splitlines():
        if not line.startswith("RAW:"):
            continue
        toks = line.split()
        # toks[0]=RAW: toks[1]=id  toks[2]=ms  toks[3]=freq_hz
        # toks[4]=N:...  toks[5]=I:...  toks[6]=conf%  toks[7]=freqval
        # toks[8]=n_symbols  toks[9]=bits
        try:
            time_ms = float(toks[2])
            freq_hz = int(toks[3])
            n_symbols = int(toks[8])
            bits = toks[9]
            if not all(c in "01" for c in bits):
                continue
            # confidence percent from toks[6] (e.g. "98%")
            conf = int(toks[6].rstrip("%"))
            # SNR is toks[4] like "N:23.53+07.29" (snr+freq_offset)
            snr = float(toks[4].split(":")[1].split("+")[0])
        except (IndexError, ValueError):
            continue
        out.append({
            "time_ms": time_ms,
            "freq_hz": freq_hz,
            "n_symbols": n_symbols,
            "bits": bits,
            "conf": conf,
            "snr": snr,
            "raw_line": line,
        })
    return out


def find_ida_dl_in_parsed(parsed_path: Path) -> set[tuple[float, int]]:
    """Return (time_ms, freq_hz) tuples that classify as 'IDA: ... DL ...'."""
    out = set()
    for line in parsed_path.read_text().splitlines():
        if not line.startswith("IDA:"):
            continue
        toks = line.split()
        try:
            t = float(toks[2])
            f = int(toks[3])
            # parser uses different formatting for direction; check for DL
            if " DL " not in line:
                continue
            out.add((t, f))
        except (IndexError, ValueError):
            continue
    return out


def emit_int16_iq_header(name: str, iq: np.ndarray, source_note: str) -> str:
    assert iq.dtype == np.int16
    lines = [f"// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
             f"// Source: {source_note}",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {len(iq)};",
             f"const int16_t {name}[{len(iq)}] = {{"]
    for i in range(0, len(iq), 8):
        chunk = iq[i : i + 8]
        lines.append("  " + ",".join(f"{int(x):d}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_uint8_iq_header(name: str, iq: np.ndarray, source_note: str) -> str:
    assert iq.dtype == np.uint8
    lines = [f"// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
             f"// Source: {source_note}",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {len(iq)};",
             f"const uint8_t {name}[{len(iq)}] = {{"]
    for i in range(0, len(iq), 16):
        chunk = iq[i : i + 16]
        lines.append("  " + ",".join(f"0x{x:02x}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_bits_header(name: str, bits: str, direction: str, source_note: str) -> str:
    n = len(bits)
    lines = [f"// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
             f"// Source: {source_note}",
             f"// Direction: {direction}",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {n};",
             f"const char {name}_DIRECTION[] = \"{direction}\";",
             f"const uint8_t {name}[{n}] = {{"]
    for i in range(0, n, 32):
        chunk = bits[i : i + 32]
        lines.append("  " + ",".join(c for c in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


STRIPE_CENTERS_HZ = [
    1_617_000_000,    # covers 1615.72 - 1618.28 MHz
    1_618_280_000,
    1_619_560_000,
    1_620_840_000,
    1_622_120_000,
    1_623_400_000,
    1_624_680_000,
    1_625_960_000,    # covers 1624.68 - 1627.24 MHz
]
# Each stripe is 2.56 MHz wide; consecutive centers differ by 1.28 MHz =
# 50% overlap. Together they cover 1615.72 - 1627.24 MHz, which fully
# spans the Iridium downlink (1616 - 1626.5 MHz) with margin.


def main() -> int:
    meta = load_meta()
    src_rate = float(meta["global"]["core:sample_rate"])     # 12_000_000
    center_freq = float(meta["captures"][0]["core:frequency"])  # 1_621_500_000
    print(f"source: {src_rate/1e6:g} MSPS @ {center_freq/1e6:g} MHz center")

    bursts = parse_bits_file(BITS_PATH)
    if not bursts:
        print("ERROR: no parseable bursts in iridium.bits", file=sys.stderr)
        return 1
    ida_dl = find_ida_dl_in_parsed(PARSED_PATH)
    # Pick the highest-SNR IDA-DL burst whose (time, freq) appears in the
    # parsed output, i.e. one that successfully decoded all the way through
    # iridium-toolkit. That gives us a known-good ground truth.
    candidates = []
    for b in bursts:
        # parsed.txt time format is `000000701.8825` - matches bits time_ms.
        for (t, f) in ida_dl:
            if abs(t - b["time_ms"]) < 0.001 and f == b["freq_hz"]:
                candidates.append(b)
                break
    if not candidates:
        print("ERROR: no IDA-DL burst with matching ground truth", file=sys.stderr)
        return 1
    candidates.sort(key=lambda b: (-b["snr"], -b["conf"]))
    best = candidates[0]
    print(f"selected burst: t={best['time_ms']:.4f} ms, "
          f"f={best['freq_hz']/1e6:.4f} MHz, SNR={best['snr']:.2f} dB, "
          f"conf={best['conf']}%, n_symbols={best['n_symbols']}, "
          f"n_bits={len(best['bits'])}")

    cf32 = np.fromfile(DATA_PATH, dtype=np.complex64)
    print(f"loaded {len(cf32)} cf32 samples = {len(cf32)/src_rate:.3f} s")

    # Time window: 3 ms before the gr-iridium-reported burst time (preamble
    # margin so qpsk_demod can slide-align on the UW), tail = symbol-count
    # duration + 1 ms.
    burst_time_s = best["time_ms"] / 1000.0
    burst_dur_s = best["n_symbols"] / 25_000.0   # 25 ksym/s
    # 10 ms head margin: gives the PLL inside qpsk_demod ~250 complex
    # samples of pre-UW signal to converge on (BPSK chirp preamble that
    # precedes the UW in real Iridium bursts). Less than ~5 ms isn't
    # enough; the UW check sees an unlocked PLL and rejects all 4
    # rotations.
    head_margin_s = 0.010
    tail_margin_s = 0.005

    s_start = int(round((burst_time_s - head_margin_s) * src_rate))
    s_end   = int(round((burst_time_s + burst_dur_s + tail_margin_s) * src_rate))
    s_start = max(0, s_start)
    s_end   = min(len(cf32), s_end)
    slice_cf32 = cf32[s_start:s_end].astype(np.complex64)
    print(f"slice: cf32 samples [{s_start}..{s_end}) = {len(slice_cf32)} samples "
          f"= {len(slice_cf32)/src_rate*1000:.2f} ms")

    # Frequency shift to bring this channel to baseband.
    # +shift_hz = -(burst_freq - center_freq) so burst lands at DC after shift.
    shift_hz = center_freq - best["freq_hz"]
    n = np.arange(len(slice_cf32), dtype=np.float64)
    phasor = np.exp(-2j * np.pi * (-shift_hz) / src_rate * n).astype(np.complex64)
    shifted = (slice_cf32 * phasor).astype(np.complex64)
    print(f"freq-shifted by {shift_hz/1e3:+.1f} kHz "
          f"({best['freq_hz']/1e6:.4f} MHz -> baseband)")

    # Decimate 12 MSPS -> 50 ksps (factor 240). resample_poly applies its
    # own anti-alias filter; we don't need a separate one.
    target_2sps_rate = 50_000
    decim = int(round(src_rate / target_2sps_rate))
    assert decim * target_2sps_rate == int(src_rate), (decim, src_rate)
    decimated = resample_poly(shifted, up=1, down=decim).astype(np.complex64)
    print(f"decimated by {decim} -> {target_2sps_rate/1000:g} ksps "
          f"({len(decimated)} complex samples)")

    # Quantise to int16 with full-scale = 0.5× max magnitude (PLL transient
    # headroom, matching build_fixtures.py).
    scale = 32767.0 / max(0.5, float(np.max(np.abs(decimated))))
    iq_int16 = np.zeros(2 * len(decimated), dtype=np.int16)
    iq_int16[0::2] = np.clip(np.real(decimated) * scale, -32767, 32767).astype(np.int16)
    iq_int16[1::2] = np.clip(np.imag(decimated) * scale, -32767, 32767).astype(np.int16)
    print(f"int16 IQ: {len(iq_int16)} elements ({len(iq_int16)//2} complex), scale={scale:.1f}")

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    iq_out = FIXTURE_DIR / "fixture_albq_2sps.h"
    iq_out.write_text(emit_int16_iq_header(
        "ALBQ_2SPS", iq_int16,
        f"test_data/iridium_downlink_2022-03-17_albuquerque/iridium_cf32.sigmf-data, "
        f"burst at t={best['time_ms']:.2f} ms f={best['freq_hz']/1e6:.4f} MHz"
    ))
    print(f"wrote {iq_out}")

    truth_out = FIXTURE_DIR / "fixture_albq_truth.h"
    truth_out.write_text(emit_bits_header(
        "ALBQ_TRUTH_BITS", best["bits"], "DL",
        "gr-iridium iridium-extractor RAW line for the same burst "
        f"(t={best['time_ms']:.2f} ms, f={best['freq_hz']/1e6:.4f} MHz, "
        f"SNR={best['snr']:.2f} dB, conf={best['conf']}%)"
    ))
    print(f"wrote {truth_out}")

    # ---- Target-side fixtures: 8 stripes covering 1615.72-1627.24 MHz at
    # 2.56 MSPS uint8 IQ (50% overlap). Each stripe shifts a different 2.56
    # MHz subband to baseband, then resamples + quantises. The smoke test
    # iterates through all 8 stripes, asserting that *some* in-band burst
    # is detected on each (most stripes catch ≥1 burst from the active
    # 1149-1159 ms window).
    target_rate = 2_560_000
    TARGET_BYTES = 3 * 16384       # 49152 = 3 × 16 KB transfers = 9.6 ms
    # Use the same time anchor as the host fixture (centred on the gr-
    # iridium-selected high-SNR burst). Many other concurrent bursts at
    # other freqs land in the same 9.6 ms window.
    target_pre_ms  = 1.0
    target_post_ms = 8.6           # widen tail to 9.6 ms total slice
    t_start = int(round((burst_time_s - target_pre_ms/1000.0) * src_rate))
    t_end   = int(round((burst_time_s + target_post_ms/1000.0) * src_rate))
    t_start = max(0, t_start)
    t_end   = min(len(cf32), t_end)
    target_slice = cf32[t_start:t_end].astype(np.complex64)

    from math import gcd
    g = gcd(int(src_rate), target_rate)
    up_t = target_rate // g
    down_t = int(src_rate) // g

    # For each stripe: compute relative shift, apply phasor, resample,
    # quantise, emit one C header. Also collect per-stripe expected-burst
    # counts (gr-iridium bursts in the 9.6 ms window whose freq lies in
    # the stripe's ±1.28 MHz half-bandwidth).
    win_lo_ms = (burst_time_s - target_pre_ms/1000.0) * 1000.0
    win_hi_ms = (burst_time_s + target_post_ms/1000.0) * 1000.0
    stripe_meta = []
    for stripe_idx, stripe_center in enumerate(STRIPE_CENTERS_HZ):
        rel_shift_hz = center_freq - stripe_center      # bring stripe -> DC
        n2 = np.arange(len(target_slice), dtype=np.float64)
        ph = np.exp(-2j * np.pi * (-rel_shift_hz) / src_rate * n2).astype(np.complex64)
        shifted = (target_slice * ph).astype(np.complex64)
        dec = resample_poly(shifted, up=up_t, down=down_t).astype(np.complex64)
        scale = 100.0 / max(0.5, float(np.max(np.abs(dec))))
        re = np.clip(np.real(dec) * scale + 128.5, 0, 255).astype(np.uint8)
        im = np.clip(np.imag(dec) * scale + 128.5, 0, 255).astype(np.uint8)
        bytes_iq = np.zeros(2 * len(dec), dtype=np.uint8)
        bytes_iq[0::2] = re
        bytes_iq[1::2] = im
        if len(bytes_iq) >= TARGET_BYTES:
            bytes_iq = bytes_iq[:TARGET_BYTES]
        else:
            pad = np.full(TARGET_BYTES - len(bytes_iq), 128, dtype=np.uint8)
            bytes_iq = np.concatenate([bytes_iq, pad])

        # Bursts in time window AND within stripe ±1.28 MHz
        in_stripe = [
            b for b in bursts
            if win_lo_ms <= b["time_ms"] <= win_hi_ms
            and abs(b["freq_hz"] - stripe_center) <= 1_280_000
        ]
        sym_var = f"ALBQ_STRIPE_{stripe_idx}_UINT8"
        out = FIXTURE_DIR / f"fixture_albq_stripe_{stripe_idx}.h"
        out.write_text(emit_uint8_iq_header(
            sym_var, bytes_iq,
            f"Albuquerque cf32, stripe {stripe_idx} center "
            f"{stripe_center/1e6:.3f} MHz, time window "
            f"{win_lo_ms:.2f}..{win_hi_ms:.2f} ms, "
            f"{len(in_stripe)} gr-iridium bursts in stripe band"
        ))
        stripe_meta.append({
            "idx": stripe_idx,
            "center_hz": stripe_center,
            "expected_bursts": len(in_stripe),
            "filename": out.name,
        })
        print(f"stripe {stripe_idx}: center={stripe_center/1e6:.3f} MHz, "
              f"{len(in_stripe)} expected bursts, wrote {out.name}")

    # Generate the master include header that brings them all together.
    meta_lines = [
        "// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
        "// Master index for the Albuquerque multi-stripe fixtures.",
        "#pragma once",
        "#include <stdint.h>",
    ]
    for s in stripe_meta:
        meta_lines.append(f'#include "fixture_albq_stripe_{s["idx"]}.h"')
    meta_lines.append("")
    meta_lines.append(f"#define ALBQ_NUM_STRIPES {len(stripe_meta)}")
    meta_lines.append("")
    meta_lines.append("typedef struct {")
    meta_lines.append("    const uint8_t   *data;")
    meta_lines.append("    unsigned int     len;")
    meta_lines.append("    uint32_t         center_hz;")
    meta_lines.append("    int              expected_bursts;")
    meta_lines.append("} albq_stripe_t;")
    meta_lines.append("")
    meta_lines.append(f"static const albq_stripe_t ALBQ_STRIPES[ALBQ_NUM_STRIPES] = {{")
    for s in stripe_meta:
        meta_lines.append(
            f'    {{ ALBQ_STRIPE_{s["idx"]}_UINT8, ALBQ_STRIPE_{s["idx"]}_UINT8_LEN, '
            f'{s["center_hz"]}u, {s["expected_bursts"]} }},'
        )
    meta_lines.append("};")
    meta_path = FIXTURE_DIR / "fixture_albq_stripes.h"
    meta_path.write_text("\n".join(meta_lines) + "\n")
    print(f"wrote master index {meta_path}")

    total_expected = sum(s["expected_bursts"] for s in stripe_meta)
    print(f"total expected bursts across all stripes (with overlap double-counting): "
          f"{total_expected}")

    # ---- Raw-mode fixture for end-to-end IQ -> ACARS smoke testing.
    # Unlike the 8-stripe fixtures (which are pre-shifted so each stripe's
    # subband sits at DC for the FFT detector test), this fixture is the
    # cf32 simply downconverted + decimated AS IF an SDR had been tuned
    # to a chosen LO. Bursts appear at their natural frequency offsets
    # in the 2.56 MHz subband, so the worker's freq-centering chain
    # works correctly — needed for end-to-end qpsk_demod / BCH /
    # frame_decoder validation on real silicon.
    #
    # LO choice: 1618.5 MHz (centred on the dense burst cluster around
    # 1618 MHz visible in iridium.bits). Bursts in 1617.22-1619.78 MHz
    # are passed through; bursts outside that window are filtered out
    # by the polyphase anti-alias filter at decimation.
    raw_lo_hz = 1_618_500_000
    print(f"raw-mode fixture: LO={raw_lo_hz/1e6:.3f} MHz (covers "
          f"{(raw_lo_hz - target_rate/2)/1e6:.3f}-"
          f"{(raw_lo_hz + target_rate/2)/1e6:.3f} MHz)")

    # Use the same time window as the stripe fixtures (9.6 ms covering
    # the burst-rich 1149-1159 ms region).
    raw_slice = cf32[t_start:t_end].astype(np.complex64)
    raw_shift = center_freq - raw_lo_hz
    n_raw = np.arange(len(raw_slice), dtype=np.float64)
    raw_phasor = np.exp(-2j * np.pi * (-raw_shift) / src_rate * n_raw).astype(np.complex64)
    raw_shifted = raw_slice * raw_phasor
    raw_dec = resample_poly(raw_shifted, up=up_t, down=down_t).astype(np.complex64)
    raw_scale = 100.0 / max(0.5, float(np.max(np.abs(raw_dec))))
    raw_re = np.clip(np.real(raw_dec) * raw_scale + 128.5, 0, 255).astype(np.uint8)
    raw_im = np.clip(np.imag(raw_dec) * raw_scale + 128.5, 0, 255).astype(np.uint8)
    raw_bytes = np.zeros(2 * len(raw_dec), dtype=np.uint8)
    raw_bytes[0::2] = raw_re
    raw_bytes[1::2] = raw_im
    if len(raw_bytes) >= TARGET_BYTES:
        raw_bytes = raw_bytes[:TARGET_BYTES]
    else:
        pad = np.full(TARGET_BYTES - len(raw_bytes), 128, dtype=np.uint8)
        raw_bytes = np.concatenate([raw_bytes, pad])

    # Find bursts in the raw subband — within ±1.28 MHz of the LO.
    raw_burst_count = sum(
        1 for b in bursts
        if win_lo_ms <= b["time_ms"] <= win_hi_ms
        and abs(b["freq_hz"] - raw_lo_hz) <= 1_280_000
    )
    print(f"  expected bursts in raw subband: {raw_burst_count}")

    raw_path = FIXTURE_DIR / "fixture_albq_raw.h"
    raw_lines = [
        "// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
        "// Raw-mode fixture: cf32 simply downconverted to 2.56 MSPS at a fixed LO,",
        "// no per-burst pre-shift. Used for end-to-end IQ -> ACARS smoke testing",
        "// where the worker's freq-centering chain expects natural bin offsets.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define ALBQ_RAW_LO_HZ           {raw_lo_hz}u",
        f"#define ALBQ_RAW_SAMPLE_RATE_HZ  {target_rate}u",
        f"#define ALBQ_RAW_EXPECTED_BURSTS {raw_burst_count}",
        "",
    ]
    raw_lines.append(emit_uint8_iq_header(
        "ALBQ_RAW_UINT8", raw_bytes,
        f"Albuquerque cf32, downconverted at LO={raw_lo_hz/1e6:.3f} MHz, "
        f"decimated 12 MSPS -> 2.56 MSPS, no per-burst pre-shift, "
        f"{raw_burst_count} bursts in subband"
    ))
    raw_path.write_text("\n".join(raw_lines) + "\n")
    print(f"wrote raw-mode fixture {raw_path}")

    # ---- Frame-classifier corpus: every bit string from iridium.bits
    # paired with its iridium-parser-classified frame type. Used by
    # tests/host/test_iridium_frame_corpus.c to regress our top-level
    # classifier against the upstream reference.
    parsed_lines = PARSED_PATH.read_text().splitlines()
    # Map from (time_ms, freq_hz) to (parser_class, direction). Direction
    # comes from " UL " or " DL " token in the parser body — matters for
    # the strict-UW gate which compares bits[0..23] to the canonical
    # DL or UL UW pattern.
    parser_info_for = {}
    for line in parsed_lines:
        toks = line.split()
        if len(toks) < 4:
            continue
        prefix = toks[0].rstrip(":")
        try:
            t = float(toks[2])
            f = int(toks[3])
        except ValueError:
            continue
        # Search the body for direction tokens.
        if " UL " in line:
            direction = "UL"
        elif " DL " in line:
            direction = "DL"
        else:
            direction = "DL"   # default for unparseable / RAW lines
        parser_info_for[(round(t, 4), f)] = (prefix, direction)

    frame_corpus = []
    for b in bursts:
        key = (round(b["time_ms"], 4), b["freq_hz"])
        parser_class, direction = parser_info_for.get(key, ("UNK", "DL"))
        # Map parser class -> our top-level classifier expected output
        #   IRA/IMS -> MS         (messaging frames)
        #   IRI/ITL -> TL         (time/location)
        #   IBC     -> BC         (broadcast)
        #   IDA/ISY/IIU/I36/IVO/IIP/INX -> LW   (LCW frames)
        #   RAW/UNK/<anything else> -> UNKNOWN
        ms_classes = {"IRA", "IMS"}
        tl_classes = {"IRI", "ITL"}
        bc_classes = {"IBC"}
        lw_classes = {"IDA", "ISY", "IIU", "I36", "IVO", "IIP", "INX"}
        if parser_class in ms_classes:
            expected = "IR_FRAME_MS"
        elif parser_class in tl_classes:
            expected = "IR_FRAME_TL"
        elif parser_class in bc_classes:
            expected = "IR_FRAME_BC"
        elif parser_class in lw_classes:
            expected = "IR_FRAME_LW"
        else:
            expected = "IR_FRAME_UNKNOWN"
        frame_corpus.append({
            "bits":      b["bits"],
            "expected":  expected,
            "parser":    parser_class,
            "direction": direction,    # "DL" or "UL"
            "snr":       b["snr"],
            "freq":      b["freq_hz"],
            "time_ms":   b["time_ms"],
        })

    fc_path = FIXTURE_DIR / "fixture_albq_frames_corpus.h"
    fc_lines = [
        "// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
        "// Source: test_data/iridium_downlink_2022-03-17_albuquerque/derivations/iridium.bits",
        "//         + iridium.parsed for ground-truth classification.",
        "// Used by tests/host/test_iridium_frame_corpus.c to regress the",
        "// top-level frame classifier against the upstream parser.",
        "#pragma once",
        "#include <stdint.h>",
        "#include \"iridium_frame.h\"",
        "",
        "typedef struct {",
        "    const uint8_t       *bits;",
        "    unsigned int         n_bits;",
        "    ir_frame_type_t      expected_type;",
        "    ir_frame_direction_t expected_direction;",
        "    const char          *parser_class;     // 'IRA','IDA',...",
        "    float                snr_db;",
        "    uint32_t             freq_hz;",
        "    float                time_ms;",
        "} albq_frame_corpus_entry_t;",
        "",
    ]
    # One static array of bits per entry, then the metadata array.
    for i, e in enumerate(frame_corpus):
        bits_packed = ",".join(c for c in e["bits"])
        fc_lines.append(f"static const uint8_t ALBQ_FC_{i}_BITS[{len(e['bits'])}] = {{ {bits_packed} }};")
    fc_lines.append("")
    fc_lines.append(f"#define ALBQ_FRAME_CORPUS_LEN {len(frame_corpus)}")
    fc_lines.append("static const albq_frame_corpus_entry_t ALBQ_FRAME_CORPUS[ALBQ_FRAME_CORPUS_LEN] = {")
    for i, e in enumerate(frame_corpus):
        dir_const = ("IR_FRM_DIR_UPLINK" if e["direction"] == "UL"
                     else "IR_FRM_DIR_DOWNLINK")
        fc_lines.append(
            f'    {{ ALBQ_FC_{i}_BITS, {len(e["bits"])}, {e["expected"]}, '
            f'{dir_const}, "{e["parser"]}", {e["snr"]:.2f}f, '
            f'{e["freq"]}u, {e["time_ms"]:.4f}f }},'
        )
    fc_lines.append("};")
    fc_path.write_text("\n".join(fc_lines) + "\n")
    print(f"wrote frame corpus {fc_path} ({len(frame_corpus)} entries)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
