#!/usr/bin/env python3
"""
Build a host-test fixture from the Albuquerque cf32 capture
(test_data/iridium_downlink_2022-03-17_albuquerque/iridium_cf32.sigmf-data).

Strategy: pick the highest-SNR IDA-DL burst gr-iridium found in the file
(by scanning derivations/iridium.bits), frequency-shift its slice from the
12 MSPS wideband recording to baseband, decimate to 50 ksps (2 sps at the
25 ksym/s symbol rate), and emit:

  - tests/fixtures/fixture_albq_2sps.h     : int16 IQ for qpsk_demod
  - tests/fixtures/fixture_albq_truth.h    : ground truth bits + direction

Usage: tests/scripts/build_albq_fixture.py
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

import numpy as np
from scipy.signal import resample_poly

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SRC_DIR = REPO_ROOT / "test_data" / "iridium_downlink_2022-03-17_albuquerque"
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures"

DATA_PATH = SRC_DIR / "iridium_cf32.sigmf-data"
META_PATH = SRC_DIR / "iridium_cf32.sigmf-meta"
BITS_PATH = SRC_DIR / "derivations" / "iridium.bits"
PARSED_PATH = SRC_DIR / "derivations" / "iridium.parsed"


def load_meta() -> dict:
    meta = json.loads(META_PATH.read_text())
    assert meta["global"]["core:datatype"] == "cf32_le"
    return meta


def parse_bits_file(path: Path) -> list[dict]:
    """
    Each line of iridium.bits looks like:
      RAW: i-<id>-t1 <ms> <freq_hz> N:<snr+offset> I:<idx> <conf>%
           <freqval> <n_symbols> <bit_string>
    We need ms, freq_hz, n_symbols, bits.
    """
    out = []
    for line in path.read_text().splitlines():
        if not line.startswith("RAW:"):
            continue
        toks = line.split()
        # toks[0]=RAW: toks[1]=id  toks[2]=ms  toks[3]=freq_hz
        # toks[4]=N:...  toks[5]=I:...  toks[6]=conf%  toks[7]=freqval
        # toks[8]=n_symbols  toks[9]=bits
        try:
            time_ms = float(toks[2])
            freq_hz = int(toks[3])
            n_symbols = int(toks[8])
            bits = toks[9]
            if not all(c in "01" for c in bits):
                continue
            # confidence percent from toks[6] (e.g. "98%")
            conf = int(toks[6].rstrip("%"))
            # SNR is toks[4] like "N:23.53+07.29" (snr+freq_offset)
            snr = float(toks[4].split(":")[1].split("+")[0])
        except (IndexError, ValueError):
            continue
        out.append({
            "time_ms": time_ms,
            "freq_hz": freq_hz,
            "n_symbols": n_symbols,
            "bits": bits,
            "conf": conf,
            "snr": snr,
            "raw_line": line,
        })
    return out


def find_ida_dl_in_parsed(parsed_path: Path) -> set[tuple[float, int]]:
    """Return (time_ms, freq_hz) tuples that classify as 'IDA: ... DL ...'."""
    out = set()
    for line in parsed_path.read_text().splitlines():
        if not line.startswith("IDA:"):
            continue
        toks = line.split()
        try:
            t = float(toks[2])
            f = int(toks[3])
            # parser uses different formatting for direction; check for DL
            if " DL " not in line:
                continue
            out.add((t, f))
        except (IndexError, ValueError):
            continue
    return out


def emit_int16_iq_header(name: str, iq: np.ndarray, source_note: str) -> str:
    assert iq.dtype == np.int16
    lines = [f"// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
             f"// Source: {source_note}",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {len(iq)};",
             f"const int16_t {name}[{len(iq)}] = {{"]
    for i in range(0, len(iq), 8):
        chunk = iq[i : i + 8]
        lines.append("  " + ",".join(f"{int(x):d}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_bits_header(name: str, bits: str, direction: str, source_note: str) -> str:
    n = len(bits)
    lines = [f"// Auto-generated by tests/scripts/build_albq_fixture.py — do not edit by hand.",
             f"// Source: {source_note}",
             f"// Direction: {direction}",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {n};",
             f"const char {name}_DIRECTION[] = \"{direction}\";",
             f"const uint8_t {name}[{n}] = {{"]
    for i in range(0, n, 32):
        chunk = bits[i : i + 32]
        lines.append("  " + ",".join(c for c in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    meta = load_meta()
    src_rate = float(meta["global"]["core:sample_rate"])     # 12_000_000
    center_freq = float(meta["captures"][0]["core:frequency"])  # 1_621_500_000
    print(f"source: {src_rate/1e6:g} MSPS @ {center_freq/1e6:g} MHz center")

    bursts = parse_bits_file(BITS_PATH)
    if not bursts:
        print("ERROR: no parseable bursts in iridium.bits", file=sys.stderr)
        return 1
    ida_dl = find_ida_dl_in_parsed(PARSED_PATH)
    # Pick the highest-SNR IDA-DL burst whose (time, freq) appears in the
    # parsed output, i.e. one that successfully decoded all the way through
    # iridium-toolkit. That gives us a known-good ground truth.
    candidates = []
    for b in bursts:
        # parsed.txt time format is `000000701.8825` - matches bits time_ms.
        for (t, f) in ida_dl:
            if abs(t - b["time_ms"]) < 0.001 and f == b["freq_hz"]:
                candidates.append(b)
                break
    if not candidates:
        print("ERROR: no IDA-DL burst with matching ground truth", file=sys.stderr)
        return 1
    candidates.sort(key=lambda b: (-b["snr"], -b["conf"]))
    best = candidates[0]
    print(f"selected burst: t={best['time_ms']:.4f} ms, "
          f"f={best['freq_hz']/1e6:.4f} MHz, SNR={best['snr']:.2f} dB, "
          f"conf={best['conf']}%, n_symbols={best['n_symbols']}, "
          f"n_bits={len(best['bits'])}")

    cf32 = np.fromfile(DATA_PATH, dtype=np.complex64)
    print(f"loaded {len(cf32)} cf32 samples = {len(cf32)/src_rate:.3f} s")

    # Time window: 3 ms before the gr-iridium-reported burst time (preamble
    # margin so qpsk_demod can slide-align on the UW), tail = symbol-count
    # duration + 1 ms.
    burst_time_s = best["time_ms"] / 1000.0
    burst_dur_s = best["n_symbols"] / 25_000.0   # 25 ksym/s
    # 10 ms head margin: gives the PLL inside qpsk_demod ~250 complex
    # samples of pre-UW signal to converge on (BPSK chirp preamble that
    # precedes the UW in real Iridium bursts). Less than ~5 ms isn't
    # enough; the UW check sees an unlocked PLL and rejects all 4
    # rotations.
    head_margin_s = 0.010
    tail_margin_s = 0.005

    s_start = int(round((burst_time_s - head_margin_s) * src_rate))
    s_end   = int(round((burst_time_s + burst_dur_s + tail_margin_s) * src_rate))
    s_start = max(0, s_start)
    s_end   = min(len(cf32), s_end)
    slice_cf32 = cf32[s_start:s_end].astype(np.complex64)
    print(f"slice: cf32 samples [{s_start}..{s_end}) = {len(slice_cf32)} samples "
          f"= {len(slice_cf32)/src_rate*1000:.2f} ms")

    # Frequency shift to bring this channel to baseband.
    # +shift_hz = -(burst_freq - center_freq) so burst lands at DC after shift.
    shift_hz = center_freq - best["freq_hz"]
    n = np.arange(len(slice_cf32), dtype=np.float64)
    phasor = np.exp(-2j * np.pi * (-shift_hz) / src_rate * n).astype(np.complex64)
    shifted = (slice_cf32 * phasor).astype(np.complex64)
    print(f"freq-shifted by {shift_hz/1e3:+.1f} kHz "
          f"({best['freq_hz']/1e6:.4f} MHz -> baseband)")

    # Decimate 12 MSPS -> 50 ksps (factor 240). resample_poly applies its
    # own anti-alias filter; we don't need a separate one.
    target_2sps_rate = 50_000
    decim = int(round(src_rate / target_2sps_rate))
    assert decim * target_2sps_rate == int(src_rate), (decim, src_rate)
    decimated = resample_poly(shifted, up=1, down=decim).astype(np.complex64)
    print(f"decimated by {decim} -> {target_2sps_rate/1000:g} ksps "
          f"({len(decimated)} complex samples)")

    # Quantise to int16 with full-scale = 0.5× max magnitude (PLL transient
    # headroom, matching build_fixtures.py).
    scale = 32767.0 / max(0.5, float(np.max(np.abs(decimated))))
    iq_int16 = np.zeros(2 * len(decimated), dtype=np.int16)
    iq_int16[0::2] = np.clip(np.real(decimated) * scale, -32767, 32767).astype(np.int16)
    iq_int16[1::2] = np.clip(np.imag(decimated) * scale, -32767, 32767).astype(np.int16)
    print(f"int16 IQ: {len(iq_int16)} elements ({len(iq_int16)//2} complex), scale={scale:.1f}")

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    iq_out = FIXTURE_DIR / "fixture_albq_2sps.h"
    iq_out.write_text(emit_int16_iq_header(
        "ALBQ_2SPS", iq_int16,
        f"test_data/iridium_downlink_2022-03-17_albuquerque/iridium_cf32.sigmf-data, "
        f"burst at t={best['time_ms']:.2f} ms f={best['freq_hz']/1e6:.4f} MHz"
    ))
    print(f"wrote {iq_out}")

    truth_out = FIXTURE_DIR / "fixture_albq_truth.h"
    truth_out.write_text(emit_bits_header(
        "ALBQ_TRUTH_BITS", best["bits"], "DL",
        "gr-iridium iridium-extractor RAW line for the same burst "
        f"(t={best['time_ms']:.2f} ms, f={best['freq_hz']/1e6:.4f} MHz, "
        f"SNR={best['snr']:.2f} dB, conf={best['conf']}%)"
    ))
    print(f"wrote {truth_out}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
