#!/usr/bin/env python3
"""
Build a UL-direction host-test fixture from the Albuquerque corpus.

The Albuquerque cf32 capture has exactly one UL frame (ISY at
t=958.37 ms, f=1618.4365 MHz, SNR=18.76 dB). This script slices that
burst from the 12 MSPS wideband recording, frequency-shifts it to
baseband, decimates to 50 ksps (2 sps at 25 ksym/s), and emits an
int16 IQ fixture. The companion test asserts uw_correlator's
direction discrimination picks UL on this burst — which exercises a
code path (UL sync pattern) not covered by the DL fixture.

Usage: tests/scripts/build_albq_ul_fixture.py
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

import numpy as np
from scipy.signal import resample_poly

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SRC_DIR = REPO_ROOT / "test_data" / "iridium_downlink_2022-03-17_albuquerque"
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures"

DATA_PATH = SRC_DIR / "iridium_cf32.sigmf-data"
META_PATH = SRC_DIR / "iridium_cf32.sigmf-meta"
PARSED_PATH = SRC_DIR / "derivations" / "iridium.parsed"

# Hand-selected: the only UL burst in this corpus.
TARGET_TIME_MS = 958.3697
TARGET_FREQ_HZ = 1618436515


def load_meta() -> dict:
    return json.loads(META_PATH.read_text())


def find_ul_burst() -> tuple[float, int, int, float, int]:
    """Locate the UL burst in iridium.parsed by (time, freq).
    Returns (time_ms, freq_hz, n_symbols, snr, conf%)."""
    for line in PARSED_PATH.read_text().splitlines():
        if " UL " not in line:
            continue
        toks = line.split()
        try:
            t = float(toks[2])
            f = int(toks[3])
            if abs(t - TARGET_TIME_MS) > 0.001 or f != TARGET_FREQ_HZ:
                continue
            conf = int(toks[4].rstrip("%"))
            # SNR token: "059.25|0011.11|18.76" — last field is dB SNR.
            snr = float(toks[5].split("|")[-1])
            n_symbols = int(toks[6])
            return t, f, n_symbols, snr, conf
        except (IndexError, ValueError):
            continue
    raise RuntimeError("UL burst not found in iridium.parsed")


def emit_int16_iq_header(name: str, iq: np.ndarray, source_note: str,
                          direction: str) -> str:
    assert iq.dtype == np.int16
    lines = [f"// Auto-generated by tests/scripts/build_albq_ul_fixture.py — do not edit by hand.",
             f"// Source: {source_note}",
             f"// Direction: {direction}",
             f"#include <stdint.h>",
             f"const char {name}_DIRECTION[] = \"{direction}\";",
             f"const unsigned int {name}_LEN = {len(iq)};",
             f"const int16_t {name}[{len(iq)}] = {{"]
    for i in range(0, len(iq), 8):
        chunk = iq[i : i + 8]
        lines.append("  " + ",".join(f"{int(x):d}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    meta = load_meta()
    src_rate = float(meta["global"]["core:sample_rate"])
    center_freq = float(meta["captures"][0]["core:frequency"])
    print(f"source: {src_rate/1e6:g} MSPS @ {center_freq/1e6:g} MHz center")

    time_ms, freq_hz, n_symbols, snr, conf = find_ul_burst()
    print(f"UL burst: t={time_ms:.4f} ms, f={freq_hz/1e6:.4f} MHz, "
          f"n_symbols={n_symbols}, SNR={snr:.2f} dB, conf={conf}%")

    cf32 = np.fromfile(DATA_PATH, dtype=np.complex64)
    print(f"loaded {len(cf32)} cf32 samples = {len(cf32)/src_rate:.3f} s")

    burst_time_s = time_ms / 1000.0
    burst_dur_s = n_symbols / 25_000.0
    head_margin_s = 0.010
    tail_margin_s = 0.005

    s_start = int(round((burst_time_s - head_margin_s) * src_rate))
    s_end   = int(round((burst_time_s + burst_dur_s + tail_margin_s) * src_rate))
    s_start = max(0, s_start)
    s_end   = min(len(cf32), s_end)
    slice_cf32 = cf32[s_start:s_end].astype(np.complex64)
    print(f"slice: {len(slice_cf32)} samples = {len(slice_cf32)/src_rate*1000:.2f} ms")

    shift_hz = center_freq - freq_hz
    n = np.arange(len(slice_cf32), dtype=np.float64)
    phasor = np.exp(-2j * np.pi * (-shift_hz) / src_rate * n).astype(np.complex64)
    shifted = (slice_cf32 * phasor).astype(np.complex64)
    print(f"freq-shifted by {shift_hz/1e3:+.1f} kHz")

    target_2sps_rate = 50_000
    decim = int(round(src_rate / target_2sps_rate))
    assert decim * target_2sps_rate == int(src_rate), (decim, src_rate)
    decimated = resample_poly(shifted, up=1, down=decim).astype(np.complex64)
    print(f"decimated by {decim} -> {target_2sps_rate/1000:g} ksps "
          f"({len(decimated)} complex samples)")

    scale = 32767.0 / max(0.5, float(np.max(np.abs(decimated))))
    iq_int16 = np.zeros(2 * len(decimated), dtype=np.int16)
    iq_int16[0::2] = np.clip(np.real(decimated) * scale, -32767, 32767).astype(np.int16)
    iq_int16[1::2] = np.clip(np.imag(decimated) * scale, -32767, 32767).astype(np.int16)
    print(f"int16 IQ: {len(iq_int16)//2} complex samples, scale={scale:.1f}")

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    out = FIXTURE_DIR / "fixture_albq_ul_2sps.h"
    out.write_text(emit_int16_iq_header(
        "ALBQ_UL_2SPS", iq_int16,
        f"test_data/iridium_downlink_2022-03-17_albuquerque/iridium_cf32.sigmf-data, "
        f"UL burst at t={time_ms:.2f} ms f={freq_hz/1e6:.4f} MHz SNR={snr:.1f} dB",
        "UL"
    ))
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
