#!/usr/bin/env python3
"""
Generate cross-validation data for tests/host/test_polyphase_channelizer.c
against a numpy reference implementation of the same polyphase + FFT
channelizer math.

Output: tests/fixtures/fixture_channelizer_reference.h

The fixture has:
  - REF_INPUT_LEN samples of complex input (synthetic multi-tone)
  - REF_OUTPUT[POLYCHAN_M][cycles] complex outputs from our reference
    polyphase + FFT channelizer with the SAME prototype filter our
    C implementation uses.

The C test then runs its channelizer on the same input and asserts
each output sample matches the reference within ε (allowing for
float-vs-double precision differences only — algorithm must match
bit-for-bit modulo accumulator order).
"""
import numpy as np
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
FIXTURE_DIR = REPO / "tests" / "fixtures"

M = 64
N_TAPS_PER_PHASE = 16          # was 8; matches polyphase_channelizer.h
L = M * N_TAPS_PER_PHASE     # 1024
FS_IN = 2_560_000

def build_prototype():
    """Identical to polyphase_channelizer.c:build_prototype()"""
    center = (L - 1) / 2.0
    cutoff = 1.0 / (2.0 * M)
    h = np.zeros(L)
    for k in range(L):
        t = k - center
        sinc = (2.0 * cutoff) if t == 0 else np.sin(2 * np.pi * cutoff * t) / (np.pi * t)
        w = 0.54 - 0.46 * np.cos(2 * np.pi * k / (L - 1))
        h[k] = sinc * w
    s = h.sum()
    if s != 0:
        h *= M / s
    # Polyphase decompose: h_phase[p, n] = h[n*M + p]
    h_phase = np.zeros((M, N_TAPS_PER_PHASE))
    for p in range(M):
        for n in range(N_TAPS_PER_PHASE):
            h_phase[p, n] = h[n * M + p]
    return h_phase

def channelize(input_samples, h_phase):
    """Reference: same algorithm as polyphase_channelizer.c."""
    n_input = len(input_samples)
    n_cycles = n_input // M
    out = np.zeros((n_cycles, M), dtype=np.complex128)
    # Per-phase circular delay lines
    dl = np.zeros((M, N_TAPS_PER_PHASE), dtype=np.complex128)
    head = 0
    for cycle in range(n_cycles):
        in_block = input_samples[cycle * M:(cycle + 1) * M]
        # Insert: phase p ← in_block[p]
        new_head = (head - 1 + N_TAPS_PER_PHASE) % N_TAPS_PER_PHASE
        for p in range(M):
            dl[p, new_head] = in_block[p]
        head = new_head
        # Filter per phase
        fft_buf = np.zeros(M, dtype=np.complex128)
        for p in range(M):
            acc = 0.0 + 0.0j
            for n in range(N_TAPS_PER_PHASE):
                idx = (head + n) % N_TAPS_PER_PHASE
                acc += h_phase[p, n] * dl[p, idx]
            fft_buf[p] = acc
        out[cycle] = np.fft.fft(fft_buf)
    return out

def main():
    h_phase = build_prototype()

    # Synthetic input: three concurrent tones at known frequencies, +
    # a small amount of complex Gaussian noise.
    n_input = 256 * M    # 256 cycles
    rng = np.random.default_rng(seed=42)
    sig = np.zeros(n_input, dtype=np.complex128)
    for f_hz in (+80_000, -200_000, +320_000):    # ch 2, 59, 8
        n = np.arange(n_input)
        sig += np.exp(2j * np.pi * f_hz * n / FS_IN)
    sig += 0.01 * (rng.standard_normal(n_input) + 1j * rng.standard_normal(n_input))
    sig = sig.astype(np.complex64)    # match the C side's float precision

    out = channelize(sig, h_phase)

    # Emit C header.
    out_path = FIXTURE_DIR / "fixture_channelizer_reference.h"
    lines = [
        "// Auto-generated by tests/scripts/build_channelizer_reference.py — do not edit by hand.",
        "// Cross-validation reference for tests/host/test_polyphase_channelizer.c.",
        "// Independent numpy implementation of the same polyphase + FFT math; the",
        "// C channelizer's outputs must match these within ε on the same input.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <complex.h>",
        "",
        f"#define REF_M           {M}",
        f"#define REF_N_TAPS      {N_TAPS_PER_PHASE}",
        f"#define REF_FS_IN       {FS_IN}u",
        f"#define REF_INPUT_LEN   {n_input}",
        f"#define REF_N_CYCLES    {len(out)}",
        "",
        "// Synthetic input: 3 tones (+80, -200, +320 kHz) + small Gaussian noise (σ=0.01).",
        f"static const float complex REF_INPUT[REF_INPUT_LEN] = {{",
    ]
    for i in range(0, n_input, 4):
        chunk = sig[i:i + 4]
        s = ", ".join(f"{x.real:+.6f}{x.imag:+.6f}*I" for x in chunk)
        lines.append(f"    {s},")
    lines.append("};")
    lines.append("")
    lines.append("// Reference outputs: REF_OUTPUT[cycle][channel].")
    lines.append("static const float complex REF_OUTPUT[REF_N_CYCLES][REF_M] = {")
    for cycle in range(len(out)):
        # Format one cycle's M outputs across multiple lines
        lines.append("    {")
        row = out[cycle]
        for i in range(0, M, 4):
            chunk = row[i:i + 4]
            s = ", ".join(f"{x.real:+.6f}{x.imag:+.6f}*I" for x in chunk)
            lines.append(f"        {s},")
        lines.append("    },")
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({n_input} input samples × {len(out)} cycles × {M} channels)")
    sz_kb = out_path.stat().st_size / 1024
    print(f"  fixture size: {sz_kb:.1f} KB")

if __name__ == "__main__":
    main()
