#!/usr/bin/env python3
"""
Build C-array fixtures from the test_corpus for use in regression tests.

Outputs (under tests/fixtures/):
  - fixture_corpus_2sps.h : decimated burst at 2 sps for qpsk_demod host test
  - fixture_corpus_uint8.h: quantised cf32 -> uint8 at 2.56 MSPS for the
                            target smoke test's "real signal" mode
  - fixture_ground_truth.h: expected demodulated bits

Usage: tests/scripts/build_fixtures.py
"""
from __future__ import annotations
import json
import os
import re
import struct
import sys
from pathlib import Path

import numpy as np
from scipy.signal import resample_poly

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CORPUS_DIR = REPO_ROOT / "test_corpus"
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures"


def load_sigmf() -> tuple[np.ndarray, dict]:
    meta_path = CORPUS_DIR / "prbs15-2M-20dB.sigmf-meta"
    data_path = CORPUS_DIR / "prbs15-2M-20dB.sigmf-data"
    meta = json.loads(meta_path.read_text())
    assert meta["global"]["core:datatype"] == "cf32_le"
    cf32 = np.fromfile(data_path, dtype=np.complex64)
    return cf32, meta


def find_burst(samples: np.ndarray) -> tuple[int, int]:
    """
    Smoothed-power-profile burst extraction. The corpus is a 0.7-second
    record at low SNR; the burst is only ~2× the noise floor in the
    smoothed power, not the 5–10× of a real over-air capture. We
    threshold at median + 30% of (max-median) which catches the rising
    and falling edges of the burst envelope cleanly.
    """
    power = np.abs(samples) ** 2
    win = 4096  # ~2 ms smoothing — averages out symbol-rate fluctuations
    smooth = np.convolve(power, np.ones(win) / win, mode="same")
    median = float(np.median(smooth))
    peak = float(smooth.max())
    threshold = median + 0.3 * (peak - median)
    above = smooth > threshold
    # Find longest run of True.
    runs = []
    in_run = False
    s = 0
    for i, v in enumerate(above):
        if v and not in_run:
            in_run = True
            s = i
        elif not v and in_run:
            in_run = False
            runs.append((s, i))
    if in_run:
        runs.append((s, len(above)))
    if not runs:
        raise RuntimeError("No burst found in corpus")
    longest = max(runs, key=lambda r: r[1] - r[0])
    return longest


def parse_ground_truth() -> tuple[str, str]:
    """
    Returns (direction, expected_bits) from the upstream gr-iridium /
    iridium-toolkit RAW: file.

    Format: `RAW: <id> <ts> <freq> N:... I:... <quality%> <quality val>
                  <symbol_count> <bit_string>`

    Note: the symbol_count token is the *payload* symbol count, but the
    bit_string is the full demodulated stream including the 12-symbol
    Unique Word prefix. Don't try to validate length × 2 = symbol_count
    — use the bit string directly.
    """
    text = (CORPUS_DIR / "ground_truth" / "prbs15-2M-20dB-raw.txt").read_text().strip()
    tokens = text.split()
    bits = tokens[-1]
    if not all(c in "01" for c in bits) or len(bits) < 24:
        raise RuntimeError(f"Last token is not a bit string: {bits!r}")
    parsed_text = (
        CORPUS_DIR / "ground_truth" / "prbs15-2M-20dB-parsed.txt"
    ).read_text().strip()
    direction = "DL" if " DL " in parsed_text else "UL"
    return direction, bits


def emit_c_uint8_array(name: str, data: np.ndarray) -> str:
    assert data.dtype == np.uint8
    lines = [f"// Auto-generated by tests/scripts/build_fixtures.py — do not edit by hand.",
             f"// Source: test_corpus/prbs15-2M-20dB.sigmf-data",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {len(data)};",
             f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("  " + ",".join(f"0x{x:02x}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_c_int16_array(name: str, data: np.ndarray) -> str:
    assert data.dtype == np.int16
    lines = [f"// Auto-generated by tests/scripts/build_fixtures.py — do not edit by hand.",
             f"// Source: test_corpus/prbs15-2M-20dB.sigmf-data",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {len(data)};",
             f"const int16_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 8):
        chunk = data[i : i + 8]
        lines.append("  " + ",".join(f"{int(x):d}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_c_bit_array(name: str, bits: str, direction: str) -> str:
    n = len(bits)
    lines = [f"// Auto-generated by tests/scripts/build_fixtures.py — do not edit by hand.",
             f"// Source: test_corpus/ground_truth/prbs15-2M-20dB-raw.txt",
             f"// Direction: {direction}",
             f"#include <stdint.h>",
             f"const unsigned int {name}_LEN = {n};",
             f"const char {name}_DIRECTION[] = \"{direction}\";",
             f"const uint8_t {name}[{n}] = {{"]
    for i in range(0, n, 32):
        chunk = bits[i : i + 32]
        lines.append("  " + ",".join(c for c in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    cf32, meta = load_sigmf()
    src_rate = float(meta["global"]["core:sample_rate"])
    print(f"corpus: {len(cf32)} samples @ {src_rate/1e6:g} MSPS = {len(cf32)/src_rate:.3f} s")

    burst_start, burst_end = find_burst(cf32)
    print(f"burst region: samples [{burst_start}..{burst_end}] = "
          f"{(burst_end-burst_start)/src_rate*1000:.2f} ms "
          f"({burst_end-burst_start} samples)")

    # ---- Fixture B: 2 sps int16 IQ for qpsk_demod host test ----
    # qpsk_demod expects "2 samples per symbol" at the symbol rate
    # (Iridium symbol rate ~25 ksym/s -> 50 ksps).
    # 2_000_000 / 50_000 = 40, so decimate by 40 (rational 1/40).
    # We use resample_poly with up=1, down=40 which applies a built-in
    # antialiasing filter.
    target_2sps_rate = 50_000  # 25 kHz symbol rate × 2 sps
    decim = int(round(src_rate / target_2sps_rate))  # 40
    print(f"decimating cf32 by {decim} -> {src_rate/decim/1000:g} ksps "
          f"for qpsk_demod fixture")

    # The host qpsk_demod fixture needs leading margin (so the test can
    # slide the start offset until the UW lines up — Iridium bursts have
    # a clock-recovery preamble before the UW). The target detector
    # fixture wants no leading margin (else the first 16 KB transfer is
    # mostly pre-burst noise, the detector fires on random spectrum).
    head_margin = int(0.003 * src_rate)  # 3 ms for host fixture only
    tail_margin = int(0.001 * src_rate)  # 1 ms common
    burst_cf32_with_margin = cf32[max(0, burst_start - head_margin)
                                  : min(len(cf32), burst_end + tail_margin)]
    burst_cf32_tight       = cf32[burst_start
                                  : min(len(cf32), burst_end + tail_margin)]
    # Default name for the qpsk_demod fixture path:
    burst_cf32 = burst_cf32_with_margin

    decimated = resample_poly(burst_cf32, up=1, down=decim).astype(np.complex64)
    # Quantise to int16 with full-scale = 0.5 (most cf32 corpus is in
    # [-1, 1]; the 0.5 scale leaves headroom for the PLL transient).
    scale = 32767.0 / max(0.5, np.max(np.abs(decimated)))
    iq_int16 = np.zeros(2 * len(decimated), dtype=np.int16)
    iq_int16[0::2] = np.clip(np.real(decimated) * scale, -32767, 32767).astype(np.int16)
    iq_int16[1::2] = np.clip(np.imag(decimated) * scale, -32767, 32767).astype(np.int16)
    print(f"  -> {len(iq_int16)} int16 elements ({len(iq_int16)//2} complex)")

    out = FIXTURE_DIR / "fixture_corpus_2sps.h"
    out.write_text(emit_c_int16_array("CORPUS_2SPS", iq_int16))
    print(f"wrote {out}")

    # ---- Fixture B-low-snr: same burst with synthetic AWGN, lower SNR.
    # The 20 dB corpus is too forgiving — a regression that loses 6+ dB
    # of demod margin would still pass on it. Add white Gaussian noise
    # to the cf32 burst before decimation, targeting ~10 dB SNR (about
    # 10 dB harder than the corpus). Deterministic RNG seed so the
    # fixture is reproducible run-to-run.
    target_snr_db = 10.0
    rng = np.random.default_rng(seed=20260507)
    sig_power = float(np.mean(np.abs(burst_cf32) ** 2))
    snr_linear = 10.0 ** (target_snr_db / 10.0)
    noise_power = sig_power / snr_linear
    # Complex AWGN: real and imag each get half the total noise power.
    noise = (rng.standard_normal(len(burst_cf32))
             + 1j * rng.standard_normal(len(burst_cf32))) * np.sqrt(noise_power / 2.0)
    burst_cf32_lowsnr = burst_cf32 + noise.astype(np.complex64)
    measured_snr = 10.0 * np.log10(sig_power / float(np.mean(np.abs(noise) ** 2)))
    print(f"low-SNR fixture: signal_power={sig_power:.4f}, "
          f"noise_power={noise_power:.4f}, measured_SNR={measured_snr:.1f} dB")

    decimated_lowsnr = resample_poly(burst_cf32_lowsnr, up=1, down=decim).astype(np.complex64)
    scale_lowsnr = 32767.0 / max(0.5, np.max(np.abs(decimated_lowsnr)))
    iq_int16_lowsnr = np.zeros(2 * len(decimated_lowsnr), dtype=np.int16)
    iq_int16_lowsnr[0::2] = np.clip(np.real(decimated_lowsnr) * scale_lowsnr, -32767, 32767).astype(np.int16)
    iq_int16_lowsnr[1::2] = np.clip(np.imag(decimated_lowsnr) * scale_lowsnr, -32767, 32767).astype(np.int16)
    out = FIXTURE_DIR / "fixture_corpus_2sps_lowsnr.h"
    out.write_text(emit_c_int16_array("CORPUS_2SPS_LOWSNR", iq_int16_lowsnr))
    print(f"wrote {out}")

    # ---- Fixture A: 2.56 MSPS uint8 for target detector smoke test ----
    # Resample 2_000_000 -> 2_560_000 (32/25 ratio).
    target_target_rate = 2_560_000
    from math import gcd
    g = gcd(int(src_rate), target_target_rate)
    up_t = target_target_rate // g
    down_t = int(src_rate) // g
    print(f"resampling cf32 by {up_t}/{down_t} -> {target_target_rate/1e6:g} MSPS "
          f"for target smoke fixture")

    # For the target fixture use the tight (no head margin) crop so the
    # first 16 KB transfer of the smoke test is real burst, not noise.
    target_cf32 = resample_poly(burst_cf32_tight, up=up_t, down=down_t).astype(np.complex64)
    # uint8 IQ centred at 128, full-scale 127.
    target_scale = 100.0 / max(0.5, np.max(np.abs(target_cf32)))
    n_complex = len(target_cf32)
    target_uint8 = np.zeros(2 * n_complex, dtype=np.uint8)
    re = np.real(target_cf32) * target_scale + 128.5
    im = np.imag(target_cf32) * target_scale + 128.5
    target_uint8[0::2] = np.clip(re, 0, 255).astype(np.uint8)
    target_uint8[1::2] = np.clip(im, 0, 255).astype(np.uint8)
    # Trim to one 16 KB transfer's worth (16384 uint8 = 8192 complex).
    transfer_bytes = 16 * 1024
    if len(target_uint8) >= transfer_bytes:
        target_uint8 = target_uint8[:transfer_bytes]
    else:
        # pad with mid-scale (no signal) if the burst region is shorter
        pad = np.full(transfer_bytes - len(target_uint8), 128, dtype=np.uint8)
        target_uint8 = np.concatenate([target_uint8, pad])
    print(f"  -> {len(target_uint8)} uint8 bytes ({len(target_uint8)//2} complex)")

    out = FIXTURE_DIR / "fixture_corpus_uint8.h"
    out.write_text(emit_c_uint8_array("CORPUS_UINT8", target_uint8))
    print(f"wrote {out}")

    # ---- Ground truth bits ----
    direction, bits = parse_ground_truth()
    print(f"ground truth: {direction}, {len(bits)} bits")
    out = FIXTURE_DIR / "fixture_ground_truth.h"
    out.write_text(emit_c_bit_array("GROUND_TRUTH_BITS", bits, direction))
    print(f"wrote {out}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
