#!/usr/bin/env python3
"""Generate compile-time-constant FFT precompute tables used by
uw_correlator.c, so they can live in .rodata (flash) rather than
.bss / .ext_ram.bss (PSRAM).

Tables produced:
  s_corr_brev          uint16[CORR_FFT_N]     bit-reversal indices
  s_corr_tw_re_f       float[CORR_FFT_N / 2]  cos(-2π k / CORR_FFT_N)
  s_corr_tw_im_f       float[CORR_FFT_N / 2]  sin(-2π k / CORR_FFT_N)
  s_cfo_brev           uint16[CFO_FFT_N]      bit-reversal indices
  s_cfo_tw_re_f        float[CFO_FFT_N / 2]   cos(-2π k / CFO_FFT_N)
  s_cfo_tw_im_f        float[CFO_FFT_N / 2]   sin(-2π k / CFO_FFT_N)
  s_cfo_window_full_f  float[CFO_INPUT_N]     Blackman window
  s_cfo_window_uw_f    float[CFO_UW_ONLY_N]   Blackman window

All match the formulas in uw_correlator.c's runtime init. Run once;
the output file is committed and only needs regeneration when
CFO_FFT_N / CORR_FFT_N / CFO_INPUT_N / CFO_UW_ONLY_N change.

Usage:  python3 tests/scripts/gen_uw_correlator_tables.py

Writes: common/iridium_decoder/uw_correlator_tables.c
"""

from pathlib import Path
import math

# Must match uw_correlator.c constants.
CORR_FFT_N      = 2048
CFO_FFT_N       = 4096
CFO_INPUT_N     = 256
CFO_UW_ONLY_N   = 120

OUT_PATH = Path(__file__).resolve().parent.parent.parent / \
    "common/iridium_decoder/uw_correlator_tables.c"


def bit_reverse(n: int, log2_n: int) -> int:
    r = 0
    for _ in range(log2_n):
        r = (r << 1) | (n & 1)
        n >>= 1
    return r


def brev_table(N: int) -> list[int]:
    log2 = int(math.log2(N))
    assert (1 << log2) == N, f"N={N} not a power of two"
    return [bit_reverse(i, log2) for i in range(N)]


def twiddles(N: int) -> tuple[list[float], list[float]]:
    # Same formula as uw_correlator.c:485, 700:
    #   ang = -2.0 * pi * k / N
    re, im = [], []
    for k in range(N // 2):
        ang = -2.0 * math.pi * k / N
        re.append(math.cos(ang))
        im.append(math.sin(ang))
    return re, im


def blackman(N: int) -> list[float]:
    # Same as uw_correlator.c:712-714,720-723: standard 3-term Blackman.
    #   w[n] = 0.42 - 0.5*cos(2πn/(N-1)) + 0.08*cos(4πn/(N-1))
    out = []
    for n in range(N):
        w = (0.42
             - 0.5  * math.cos(2.0 * math.pi * n / (N - 1))
             + 0.08 * math.cos(4.0 * math.pi * n / (N - 1)))
        out.append(w)
    return out


def fmt_u16_array(name: str, length: int, values: list[int]) -> str:
    assert len(values) == length
    lines = [f"const uint16_t {name}[{length}] = {{"]
    for i in range(0, length, 16):
        chunk = ", ".join(f"{v:5d}" for v in values[i:i+16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def fmt_f32_array(name: str, length: int, values: list[float]) -> str:
    assert len(values) == length
    lines = [f"const float {name}[{length}] = {{"]
    # Use printf-style %.9e so single-precision round-trip is exact.
    for i in range(0, length, 4):
        chunk = ", ".join(f"{v:+.9e}f" for v in values[i:i+4])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    header = f"""\
// AUTO-GENERATED by tests/scripts/gen_uw_correlator_tables.py.
// Do NOT edit by hand. Regenerate if CORR_FFT_N / CFO_FFT_N /
// CFO_INPUT_N / CFO_UW_ONLY_N change in uw_correlator.c.
//
// These tables were runtime-initialised in .bss / .ext_ram.bss; the
// values are closed-form functions of the FFT size, so they're
// hoisted to .rodata (flash) to free PSRAM. Frees ~37 KiB from
// .ext_ram.bss; same size goes to flash, where L2 cache covers the
// access pattern (sequential reads in the FFT inner loop).
//
// Generator parameters (compile-time matched to uw_correlator.c):
//   CORR_FFT_N      = {CORR_FFT_N}
//   CFO_FFT_N       = {CFO_FFT_N}
//   CFO_INPUT_N     = {CFO_INPUT_N}
//   CFO_UW_ONLY_N   = {CFO_UW_ONLY_N}

#include <stdint.h>

"""

    body = []

    # CORR_FFT bit-reversal
    body.append(fmt_u16_array("s_corr_brev", CORR_FFT_N,
                              brev_table(CORR_FFT_N)))
    body.append("")
    # CORR twiddles
    cre, cim = twiddles(CORR_FFT_N)
    body.append(fmt_f32_array("s_corr_tw_re_f", CORR_FFT_N // 2, cre))
    body.append("")
    body.append(fmt_f32_array("s_corr_tw_im_f", CORR_FFT_N // 2, cim))
    body.append("")

    # CFO_FFT bit-reversal
    body.append(fmt_u16_array("s_cfo_brev", CFO_FFT_N,
                              brev_table(CFO_FFT_N)))
    body.append("")
    # CFO twiddles
    cre, cim = twiddles(CFO_FFT_N)
    body.append(fmt_f32_array("s_cfo_tw_re_f", CFO_FFT_N // 2, cre))
    body.append("")
    body.append(fmt_f32_array("s_cfo_tw_im_f", CFO_FFT_N // 2, cim))
    body.append("")

    # Blackman windows
    body.append(fmt_f32_array("s_cfo_window_full_f", CFO_INPUT_N,
                              blackman(CFO_INPUT_N)))
    body.append("")
    body.append(fmt_f32_array("s_cfo_window_uw_f", CFO_UW_ONLY_N,
                              blackman(CFO_UW_ONLY_N)))
    body.append("")

    OUT_PATH.write_text(header + "\n".join(body) + "\n")
    size = OUT_PATH.stat().st_size
    n_floats = (CORR_FFT_N // 2) * 2 + (CFO_FFT_N // 2) * 2 \
               + CFO_INPUT_N + CFO_UW_ONLY_N
    n_u16 = CORR_FFT_N + CFO_FFT_N
    flash_bytes = n_floats * 4 + n_u16 * 2
    print(f"Wrote {OUT_PATH}")
    print(f"  source size: {size} bytes")
    print(f"  flash cost:  {flash_bytes} bytes (~{flash_bytes/1024:.1f} KiB)")
    print(f"  freed from .ext_ram.bss: same {flash_bytes/1024:.1f} KiB")


if __name__ == "__main__":
    main()
